### ISSUE TITLE
Does pymodbus support to lanuch multiple tcp client with the same ip and port to connect other modbus tcp server, like modbus poll simulator?

### ISSUE THREAD

**Issue by LinusLing0910** [riptideio/pymodbus#1022]
Does pymodbus support to lanuch multiple tcp client with the same ip and port to connect other modbus tcp server, like modbus poll simulator?

**Comment by janiversen** [comment]
yes, if you talk about port= which is the port the clients connect to.

You cannot have multiple client with the same source_address (host:port) because that is not possible with sockets.

**Comment by LinusLing0910** [comment]
it there any other workaround to do like the modbus poll simulator to launch multiple client?
![image](https://user-images.githubusercontent.com/35553852/183638844-494075ac-68e0-419c-ba66-8cab13596b06.png)

**Comment by janiversen** [comment]
Why do you want to do a "workaround" ? Pymodbus support this out of the box. 

Just go ahead and write your code, with multiple client instances:
```
   client1 = ModbusTCPClient("host",port=502)
   client2 = ModbusTCPClient("host",port=502)
   client3 = ModbusTCPClient("host",port=502)
   client4 = ModbusTCPClient("host",port=502)
```

**Comment by LinusLing0910** [comment]
@janiversen so pymodbus support the host with the same ip?
