### ISSUE TITLE
no response from the remote device

### ISSUE THREAD

**Issue by sachinmishra371** [riptideio/pymodbus#1046]
i m using rs485,not connecting i tried too much. i am giving screenshot of modscan and my code 
<img width="487" alt="modscanscreenshotconfig" src="https://user-images.githubusercontent.com/64963567/185304919-b3921fb0-7410-4a21-813f-8fd44e35487a.png">
<img width="487" alt="modscanscreenshotcrcerror" src="https://user-images.githubusercontent.com/64963567/185304930-7741efde-0b90-4431-970b-978291006b0c.png">
<img width="700" alt="Screenshot 2022-08-17 162759" src="https://user-images.githubusercontent.com/64963567/185304962-1c65f890-5122-4948-802b-04fff39e6d32.png">
<img width="694" alt="modscanscreenshot" src="https://user-images.githubusercontent.com/64963567/185304979-3e99c754-b009-4b6e-a4a7-23d8ee14d712.png">
.

**Comment by swamper123** [comment]
Please don't open up an issue **and** a discussion ( #1045 ) about the same topic.
This still seems not lie a bug itself on first sight. If it might be, the discussion will be transformed as an issue.
