### ISSUE TITLE
Automate tests needs a solution for how to mock a tty port on all platforms.

### ISSUE THREAD

**Issue by janiversen** [riptideio/pymodbus#1048]
### Versions

* Python:
* OS:
* Pymodbus:
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
 # code and logs here.

```

**Comment by dhoomakethu** [comment]
There is no common solution for mocking serial ports on all 3 platforms (Linux, Windows and Mac). We can cover linux and mac with `socat` , there are unofficial ports of `socat` for windows. May be we can try that ?

**Comment by janiversen** [comment]
I was thinking of mocking py serial but an unofficial so at seems better, where can I find that?

**Comment by dhoomakethu** [comment]
https://github.com/StudioEtrange/socat-windows/blob/master/EXAMPLES
