### ISSUE TITLE
Updating Server Example does not work

### ISSUE THREAD

**Issue by shajek** [riptideio/pymodbus#1052]
### Versions

* Python: 3.7, 3.8, 3,10
* OS: ubuntu bionic
* Pymodbus: 2.5.3
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp - sync/async

### Description

I try to run example, first error is
`TypeError: ModbusDeviceIdentification.__init__() got an unexpected keyword argument 'info_name'`

when i remove that info, it ends on

```
modbusupdater.py", line 81, in run_updating_server
    loop.start(time, now=False)  # initially delay by time
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'start'
```

async/sync server have same error with info_name, but run when removed. But i am unable to run updating server example.

Thank you

**Comment by janiversen** [comment]
There have been no changes to version 2.5.3 for about the last year, you noted in another PR that the removal of twisted was causing this....but twisted was removed after 3.0.0dev4 and a very long time after 2.5.3 was frozen.

Please try with the current version or even better with dev.
