### ISSUE TITLE
Documentation often states "slave" parameter but "unit" has to be used

### ISSUE THREAD

**Issue by TheChatty** [riptideio/pymodbus#1059]
Hi... a few pages claim you have to use `slave` to specify the unit but instead it has to be `unit` to be working.

For instance [this page](https://pymodbus.readthedocs.io/en/dev/source/library/pymodbus.client.html#pymodbus.client.mixin.ModbusClientMixin.write_register) for function `write_register` (tip: [search for slave](https://pymodbus.readthedocs.io/en/dev/search.html?q=slave&check_keywords=yes&area=default) in entire documentation).

**Comment by janiversen** [comment]
Indeed on dev there are some confusion at the moment. Client only use "slave=" and Server continue for now to use "unit=". 

Also if you use the advanced client classes (call .execute manually) the request classes still uses "unit=".

We are moving from "unit=" to "slave=" but it is a process that takes a while. All Client documentation are updated, and the server documentation are not touched so are in theory also correct.

**Comment by janiversen** [comment]
If you find a place where doc says "slave=" and "unit=" is needed in practise, please let us know, your general search for "slave=" seems correct.

**Comment by TheChatty** [comment]
I already listed an example. You probably meant further examples?

**Comment by janiversen** [comment]
but your example is not wrong, that is a client function and uses slave= as documented.

**Comment by TheChatty** [comment]
I just analyzed the bytes with Wireshark... if I use slave=247 0x00 will be used. If I use unit=247 0xf7 will be used. Thus doc and code differ.

**Comment by janiversen** [comment]
Hmmm I will control write_register, sadly enough we need to catch this function by function.

**Comment by TheChatty** [comment]
Btw, `read_holding_register` is the same (needs unit= but slave= is documented). Is there a reason for the general exchange of unit with slave?

**Comment by janiversen** [comment]
yes, unit caused quite a lot of confusion because on serial lines the same thing is called slave. It dates back ton an error in the modbus documentation for tcp.

**Comment by janiversen** [comment]
please see "client_sync_basic_calls.py" 
```
rq = client.write_register(1, 10, slave=0x25)
```
generates a request for unit/slave 0x25.

```
rq = client.write_register(1, 10, unit=0x25)
```
fails with
```
WriteSingleRegisterRequest.__init__() got multiple values for argument 'unit'
```

So it seems you are not using the latest dev, or have another problem.

**Comment by TheChatty** [comment]
```
# pip list|grep pymodbus
pymodbus            3.0.0.dev4
```

The following code produces the below Wireshark captures:
```python
#!/usr/bin/env python3
from pymodbus.client.sync import ModbusTcpClient as ModbusClient

client = ModbusClient("tasmota-0bbcbe-7358", port=5020, timeout=10)
client.connect()

rr = client.read_holding_registers(0x90, 1, unit=247)
# tcp dump: 00 01 00 00 00 06 f7 03  00 90 00 01

rr = client.write_register(0x90, 0x1234, unit=247)
# tcp dump: 00 02 00 00 00 06 f7 06  00 90 12 34

rr = client.read_holding_registers(0x90, 1, slave=247)
# tcp dump: 00 01 00 00 00 06 00 03  00 90 00 01

rr = client.write_register(0x90, 0x1234, slave=247)
# tcp dump: 00 01 00 00 00 06 00 06  00 90 12 34

client.close()
```

**Comment by janiversen** [comment]
You are comparing apples and oranges !!!

You have selected "dev" in readthedocs, which is not "3.0.0.dev4" (that is quite old)

In 3.0.0.dev4 everything is still "unit="

If you want to test the newest please clone the repo and use "dev", which correspond to the "dev" documentation.

**Comment by TheChatty** [comment]
I wasn't aware of that. I just upgrade to latest git commit but the above example fails with:
```
Traceback (most recent call last):
  File "Trovis_WriteEnable_min.py", line 2, in <module>
    from pymodbus.client.sync import ModbusTcpClient as ModbusClient
      ModuleNotFoundError: No module named 'pymodbus.client.sync'
```

**Comment by janiversen** [comment]
Because there are no "Pymodbus.client.sync" it is now "Pymodbus.client" (see the documentation).

**Comment by TheChatty** [comment]
Pardon me. Now it's solved (slave= working, unit= showing error).

**Comment by dhoomakethu** [comment]
> I just analyzed the bytes with Wireshark... if I use slave=247 0x00 will be used. If I use unit=247 0xf7 will be used. Thus doc and code differ.

Note from the specs
```
The address field of a message frame contains two characters (ASCII) or eight
bits (RTU). Valid slave device addresses are in the range of 0 – 247 decimal.
The individual slave devices are assigned addresses in the range of 1 – 247.
```
Max Slave ID that can be used is 247(decimal)

**Comment by janiversen** [comment]
but 247 is legal! apart from that, the problem was something different read above please.
