### ISSUE TITLE
processIncomingPacket: Test for valid unit is somewhat broken

### ISSUE THREAD

**Issue by smurfix** [riptideio/pymodbus#1077]
### Versions

* Pymodbus: all, AFAICT, including dev as of 2022-09-05

### Description

Using a dict to store my server's units doesn't work for no good reason IMHO.

### Code and Logs

All packet processors contain this code:

```python
        if not isinstance(unit, (list, tuple)):
            unit = [unit]
```
This breaks if my server's list of units is really a dict, or a set.
I thus need to call the packet processor with `list(self.units.keys())` each time, which is decidedly sub-optimal.

Please replace with `if isinstance(unit,int)` or similar.

**Comment by janiversen** [comment]
I do not think we have documented that you can use a dict, nor do I understand the purpose. In case of a dict should the code use the key or the value, there are arguments for both…..but the code cannot know how to use a dict. I do not see the use list(dict) as suboptimal but rather needed to tell whether key/value is to be used.

You should be able to call with an int or a list[int] or a tuple[int]. The if you do not like converts a scalar int to a list which correspond to what we want.

**Comment by smurfix** [comment]
The purpose is simple, sometimes a server has units that are not consecutive. Creating a list of units for the validation step is unnecessary work if you can just pass the unit dict in. My code contains a dynamic Modbus gateway, I don't want to create a throwaway 100-element list each time I validate a packet and I don't want the server to spend useless CPU cycles scanning that list.

I don't understand your "should the code use the key or the value" question, the unit is an integer. ModbusFramer._validate_unit_id() uses a simple `self._header["uid"] in units` test. It's not used anywhere else, thus any object with a `__contains__` method should work here.

All I want is to be able to pass in any other object that has a `__contains__` method (dict, set, …) and have that work. I propose to replace the code I do not like with code I do like (`if isinstance(unit,int): unit = [unit]`) which does exactly the same thing as your code when the caller passes a single unit number in.

**Comment by janiversen** [comment]
you can make the dict as {1: “my first device”} or {“my first devic”: 1} that means using the key or the value as the unit id. A dict implies you want to store more information for each unit, but that makes it hard to guess how to access the unit id.

If you pass a dict to the lower layers I am not sure it will work in all corner cases.

You could simply keep a list and update title whenever you update the dict, that would solve your performance problem. Admitted it is not nice to duplicate data, but it is a little list and it will be a tiny bit faster than generating the list each time.

However if you feel strongly about this, PRs are welcome but do not expect us to change this.

**Comment by janiversen** [comment]
This is not a guarantee that a PR will be accepted….but if you show through added tests that there are no side effects then it will have a good chance.

**Comment by janiversen** [comment]
Closing issue. But remember Pull Requests are welcome.
