### ISSUE TITLE
ModbusTcpClient is missing a timeout parameter

### ISSUE THREAD

**Issue by Don42** [riptideio/pymodbus#109]
The connect call of the ModbusTcpClient should use `self.timeout` like the serial and UDP clients.
That means ModbusTcpClient.**init** should also take a `timeout` Keyword argument.

Changes should only be necessary at the two locations listed.
pymodbus/pymodbus/client/sync.py:139
pymodbus/pymodbus/client/sync.py:142

**Comment by a1ananth** [comment]
Consider merging this PR #140 to fix this issue.

**Comment by dhoomakethu** [comment]
Merge and fixed as part of #140
