### ISSUE TITLE
pymodbus.constants interferes with application's logging configuration

### ISSUE THREAD

**Issue by JonasNorling** [riptideio/pymodbus#1119]
### Versions

* Python: 3.10
* OS: Ubuntu Linux
* Pymodbus: 3.0.0dev5
* Modbus Hardware (if used): 

### Description

pymodbus.constants calls logging.basicConfig() on import, overriding any logging that the application attempts to configure later on. This is unexpected and a documented anti-pattern for Python logging.

There is more discussion in PR #1106, which I will close so that someone else can suggest a solution that the maintainers can agree with.

**Comment by janiversen** [comment]
"the maintainers" have suggested to embed it in a call, making it easy for not experienced users to activate, while advanced users to do whatever they like.

Please be aware, that we need the information in the log with issues...without that information we frequently cannot reproduce the issue.

If someone makes a PR that changes it to a call, I am happy to review and merge.
