### ISSUE TITLE
conda-forge release

### ISSUE THREAD

**Issue by untzag** [riptideio/pymodbus#1127]
Hello, any chance for a conda-forge release or is something holding this up?

https://github.com/conda-forge/pymodbus-feedstock/pull/6

**Comment by janiversen** [comment]
I think you are in the wrong place, this is the Pymodbus project.

We are not responsible for, nor involved in the conda-forge project.

**Comment by untzag** [comment]
OK, I'm hearing "none of the maintainers are interested in distributing to conda-forge". I'll inquire there.

**Comment by janiversen** [comment]
To be honest I have no idea what conda-forge is....and if you look in their repo they already have a pull request.

We distribute Pymodbus in pypi.
