### ISSUE TITLE
Typo in comment of client_async.py

### ISSUE THREAD

**Issue by MAKOMO** [riptideio/pymodbus#1143]
Just spotted a tiny typo in line 21. The line should refer to the async file and should read

```
    python3 server_async.py
```

and not 

```
    python3 server_sync.py
```

Thanks for your excellent work on this library! This is all very useful for many out there!

**Comment by janiversen** [comment]
Well it can be sync or async that does not matter…this is the server and not the client.

pull requests are welcome.

**Comment by MAKOMO** [comment]
Oh, right. So it should be fine as is.
