### ISSUE TITLE
Unreachable code in AsyncModbusTcpClient

### ISSUE THREAD

**Issue by WouterTuinstra** [riptideio/pymodbus#1150]
### Versions

* Pymodbus: 3.0.0

### Pymodbus Specific
* Client: tcp - async

### Description

Unreachable code in else statement due to the early return in the try statement.
This causes that there is no logging message being reported and to never reset the delay if there would be due to a temporary disconnect.

See also `_connect` function of the async TCP client 
https://github.com/riptideio/pymodbus/blob/61d9e9ac20954634a453befae50576da2333e40b/pymodbus/client/tcp.py#L82-L100

**Comment by janiversen** [comment]
Pull requests are welcome.
