### ISSUE TITLE
socket.create_connection() error

### ISSUE THREAD

**Issue by timothyarnold1983** [riptideio/pymodbus#118]
Hi,
Firstly i'm not a seasoned developer, so apologies!

I recently updated to the current version of Pymodbus and found that my basic code would silently fail when attempting a TCP connection. TCP Dump shows no packets leaving the interface, which suggested something was up with the connection.

The culprint appears to be the source_address even though it was set (or wasn't - same result). Removing it from the connect() in ModbusTCPClient - sync.py

```
        self.socket = socket.create_connection((self.host, self.port),
            timeout=Defaults.Timeout)
```

That resolved the problem.

I'm not an expert and cannot tell you why this failed. any pointers would be useful and happy to provide further detail etc.

Thanks!
Tim

**Comment by dhoomakethu** [comment]
@timothyarnold1983 , Could you please share the code snippet you are using to investigate this further. Feel free to close , if you think this is not an issue.
