### ISSUE TITLE
After the client is closed, the function will be executed again.

### ISSUE THREAD

**Issue by ElTarget** [riptideio/pymodbus#1194]
![image](https://user-images.githubusercontent.com/41426791/204079731-0a489997-212d-49b5-a9a4-ab4fd4a21cbe.png)

**Comment by janiversen** [comment]
Please add a proper debug log and tell us which version etc. you are using, as per documentation. I really cannot see what is happening.

You might refer to a wrong socket, it could be client.protocol.socket.

**Comment by ElTarget** [comment]
![image](https://user-images.githubusercontent.com/41426791/204080392-51f60d55-3fb8-4092-8f50-1ced6624ab2c.png)
My Python 3.9 and pymodbus are 3.02.
I use ModbusSerialClient:
self. client = ModbusSerialClient(……)
Close using self.client.close()
But use self.client.close(), I can still use the related function functions.

**Comment by ElTarget** [comment]
> 

![image](https://user-images.githubusercontent.com/41426791/204080873-887c90ab-6b1d-4f82-a47c-1cbc5bf8ac70.png)
The code can be this view.

**Comment by janiversen** [comment]
Yes because pymodbus detects you are not connected and reconnect automatically. It seems you did not send the full debug log, because you should have seen both the close and the reconnect.

If you do not want to communicate anymore delete the client object (or let garbage collect do it)....calling close() and then continue making function calls is not something we consider good programming.

**Comment by janiversen** [comment]
Actually what you see, is a feature for many, because when a connection breaks it automatically reopens.

**Comment by ElTarget** [comment]
> Yes because pymodbus detects you are not connected and reconnect automatically. It seems you did not send the full debug log, because you should have seen both the close and the reconnect.
> 
> If you do not want to communicate anymore delete the client object (or let garbage collect do it)....calling close() and then continue making function calls is not something we consider good programming.

Because I am cooperating with QT in the test. After clicking Disconnect, the program on another page is still sending the read message. So there will be the current situation.

**Comment by janiversen** [comment]
Well then you need to delete the client object or have a semaphore that tells if the connection is open.

We might make client.close() stricter in a future version, but that will only lead to an exception in the following calls.

**Comment by ElTarget** [comment]
> Actually what you see, is a feature for many, because when a connection breaks it automatically reopens.

So I may need to add a judgment on whether the modbus is connected during the execution of related threads.

**Comment by ElTarget** [comment]
Yes, thank you very much!

**Comment by janiversen** [comment]
No, you need to add a judgement if your application have called client.close() or if your application still consider communication valid.

**Comment by ElTarget** [comment]
> 不，如果您的应用程序调用了 client.close（） 或者您的应用程序仍然认为通信有效，则需要添加判断。



> No, you need to add a judgement if your application have called client.close() or if your application still consider communication valid.

Yes.
