### ISSUE TITLE
client.ModbusClientMixin doesn not have __init__, but ModbusBaseClient tries to call it

### ISSUE THREAD

**Issue by Cavaler** [riptideio/pymodbus#1196]
During its initialization class ModbusBaseClient tries to call super().\_\_init\_\_(), even though ModbusClientMixin does not have \_\_init\_\_().
Usually it is not a problem.

However, if later one tries to inherit from, for example, ModbusTcpClient and from another class which has \_\_init\_\_() - that class is being called twice, with unexpected consequences:

```python
from pymodbus.client.tcp import *

class SyncClientMixin:
    def __init__(self, **kwargs):
        print("This is gonna be called twice")

class TcpClientWrapper(ModbusTcpClient, SyncClientMixin):
    def __init__(self, **kwargs):
       super().__init__(**kwargs)
       SyncClientMixin.__init__(self, **kwargs)

wrap = TcpClientWrapper(host = 'localhost')
```

The resolution is to have an empty \_\_init\_\_ in ModbusClientMixin

**Comment by janiversen** [comment]
Patch available on dev, will be part of the upcoming version 3.1 due this year.
