### ISSUE TITLE
pymodbus connect PLC panasonic RTU

### ISSUE THREAD

**Issue by TQK0209** [riptideio/pymodbus#1200]
here is code:

from pymodbus.client import ModbusSerialClient as ModbusClient

client = ModbusClient(method='rtu', port='COM3', parity='N', baudrate=9600, bytesize=8, stopbits=1, timeout=0.1)
connection = client.connect()
print(connection)
read = client.read_holding_registers(200,1)
print(read)

BUG: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)

plss help me

**Comment by janiversen** [comment]
Please add debug log as pr documentation (and as I have requested now a couple of times). Your device do not respond, but without debug log, there are no way of telling why.

Your timeout is VERY low, that might be the problem, but with RS485 it can be a lot of different problems.

**Comment by TQK0209** [comment]
Even though I edited the time to be 30s, I still get the same error

**Comment by janiversen** [comment]
Show the debug log as pr documentation, if you want more help. It is impossible to guess what your problem is, when you do not provide some logging.

**Comment by TQK0209** [comment]
I haven't worked with python for a long time, hope you can understand.
Do you mean this?

Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)
WARNING:root:Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)
ERROR:root:Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)

**Comment by janiversen** [comment]
Well this is not about your python experience, you merely needs to read the documentation.

What you show is the errors, not a debug log.

I am sorry, but I cannot help you more until you at least show a debug log.


The only thing I can tell you is that your device is not responding, so please also double check the device documentation.

**Comment by TQK0209** [comment]
thank you, i will try again and ask for your help when i get it

**Comment by TQK0209** [comment]
Readout started
DEBUG:pymodbus.transaction:Current transaction state - IDLE
DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:SEND: 0x0 0x4 0x0 0x1 0x0 0x1 0x61 0xdb
DEBUG:pymodbus.client.base:New Transaction state "SENDING"
DEBUG:pymodbus.transaction:Changing transaction state from "SENDING" to "WAITING FOR REPLY"
DEBUG:pymodbus.transaction:Transaction failed. (Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)) 
DEBUG:pymodbus.framer.rtu_framer:Frame - [b''] not ready
DEBUG:pymodbus.transaction:Getting transaction 0
DEBUG:pymodbus.transaction:Changing transaction state from "PROCESSING REPLY" to "TRANSACTION_COMPLETE"
Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)

**Comment by TQK0209** [comment]
This is my debug. help me please

**Comment by TQK0209** [comment]
@janiversen

**Comment by janiversen** [comment]
As you can see in the debug log, pymodbus never receives a response. It sends the request and then awaits a response.

The reason for the missing response can be a multitude of causes, like f.x.:
- Wrong baudrate/parity/stop bits
- Wrong comm port (looks like you are using an external serial to RS485 converter)
- RS485 is not working
- Wrong wiring or missing termination of RS485
- Wrong SLAVE id (must correspond to what is configured in your device)

You need to verify all of these and if possible verify that your device receives the request and sends a response.

**Comment by TQK0209** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/110715338/205599537-3dc52c17-1e31-44f3-b6b3-b725e34e02ec.png)

from pymodbus.client import ModbusSerialClient as ModbusClient

client = ModbusClient(method='rtu', port='COM3', parity='O', baudrate=115200, bytesize=8, stopbits=1, timeout=0.1)
connection = client.connect()
print(connection)
read = client.read_holding_registers(4001,1)
print(read)

I make sure that all the parameters I set are correct, and that my PLC program is working

**Comment by TQK0209** [comment]
Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)

**Comment by TQK0209** [comment]
I really really need help.

**Comment by janiversen** [comment]
But I really cannot help you, I am not sure what you want to say with the screenshot, is that program working on your machine ? Can you do a read_holding slave 1 register 4001 with that program and get a response ?

Pymodbus is reporting that it does not receive anything, so I have no idea on how to help you, this is not a pymodbus problem. If the other program is working, then you need to find the difference.

**Comment by TQK0209** [comment]
I connected it but can't read anything

**Comment by janiversen** [comment]
And as I wrote, problem seems to be outside pymodbus. 

The only difference I see between your program and what we use is:

   client.read_holding_registers(4001, 1, slave=SLAVE)

We always have "slave=<your device>", default is 0, and your device might not like that.

**Comment by janiversen** [comment]
Did you solve your problem ?
