### ISSUE TITLE
Better Explanation of why to use strict = False on Windows machine

### ISSUE THREAD

**Issue by Conet1502** [riptideio/pymodbus#1209]
@TheChatty if you are using this on a windows machine create the client with `strict=False` . That should fix the issue you are facing.

_Originally posted by @dhoomakethu in https://github.com/riptideio/pymodbus/issues/465#issuecomment-549203909_
      

The documentation for strict does not give a good explanation of this setting
https://pymodbus.readthedocs.io/en/latest/source/library/pymodbus.client.html

**Comment by janiversen** [comment]
I think it is a correct documentation “ strict – (optional) Strict timing, 1.5 character between requests.” of course if you know the modbus protocol. Strict means there will always be a pause of 1.5 character (time depends on baudrate) between requests.

But pull requests are always welcome, if you have a better text.

**Comment by Conet1502** [comment]
I understand the protocol, but related to #465, why would this matter on a Windows vs Linux platform?

**Comment by janiversen** [comment]
#465 is based on very old code (2019), I do not think the statement is true today.

**Comment by Conet1502** [comment]
Ok, just wondering if I was missing something.

**Comment by janiversen** [comment]
and as you might have noticed it is not part of the documentation.

**Comment by janiversen** [comment]
closing issue since it isn’t a issue
