### ISSUE TITLE
ModbusSimulatorContext String Type Fails to Encode

### ISSUE THREAD

**Issue by erezblm** [riptideio/pymodbus#1210]
### Versions

* Python: 3.10.6
* OS: Linux
* Pymodbus: 3.0.2
* Modbus Hardware (if used): None

### Pymodbus Specific
* Server: tcp - async
* Client: None

### Description

I was using ModbusSimulatorContext with the settings as provided by the pymodbus documentation in this [link](https://pymodbus.readthedocs.io/en/latest/source/library/pymodbus.datastore.html#pymodbus.datastore.ModbusSimulatorContext).

All the registers were working just fine when client requested them, but the string type registers did not return anything.
After some debugging I realized that 'handle_type_string' within the ModbusSimulatorContext is setting each register with a string of 2 letters (living it as a string type).

When the 'encode' function in 'ReadRegistersResponseBase' tries to build to bytes from the registers made in ModbusSimulatorContext, it's using `struct.pack(">H", register)` over the register while the register is a string for example 'St' and it throws an exception 'required argument is not an integer'.

I managed to solve it by changing the code in ModbusSimulatorContext, see below.

### Code and Logs

Current ModbusSimulatorContext.handle_type_string function:
```python
def handle_type_string(self, registers, value, action, _entry):
    """Handle type string."""
    j = 0
    for i in range(registers[0], registers[1] + 1):
        self.registers[i].type = CELL_TYPE_STRING_NEXT
        self.registers[i].value = value[j : j + 2]
        j += 2
    self.registers[registers[0]].type = CELL_TYPE_STRING
    self.registers[registers[0]].action = action
```

Current ReadRegistersResponseBase.encode function:
```python
def encode(self):
    """Encode the response packet.

    :returns: The encoded packet
    """
    result = struct.pack(">B", len(self.registers) * 2)
    for register in self.registers:
        result += struct.pack(">H", register)
    return result
```

Suggested fix for ModbusSimulatorContext.handle_type_string function:
```python
def handle_type_string(self, registers, value, action, _entry):
    """Handle type string."""
    j = 0
    for i in range(registers[0], registers[1] + 1):
        self.registers[i].type = CELL_TYPE_STRING_NEXT
        self.registers[i].value = int.from_bytes(
            bytes(value[j : j + 2], "UTF-8"), "big"
        )
        j += 2
    self.registers[registers[0]].type = CELL_TYPE_STRING
    self.registers[registers[0]].action = action

```

**Comment by janiversen** [comment]
Thanks for your report, simulator have evolved a bit since 3.0.2, so I cannot use your code directly.

However you detected a real problem and it is solved in #1211. Be aware you cannot just cherry-pick that commit, but it will soon be available on dev.
