### ISSUE TITLE
TCP reconnect_delay changed from (100ms, 5min) to (5 min, infinite)

### ISSUE THREAD

**Issue by alexrudd2** [riptideio/pymodbus#1243]
### Versions

* Python: 3.11
* OS: macOS
* Pymodbus: newer than 3ce0dbd8f1b77cf4278fb024500ba64bd2b4ee08

### Pymodbus Specific
* async TCP client (probably affects all)

### Description

As of https://github.com/riptideio/pymodbus/pull/266, pymodbus had a minimum reconnection delay of 100ms, which doubled on every reconnection failure up to a maximum of 5min.  (This is a simple binary exponential backoff)
```python
class ReconnectingAsyncioModbusTcpClient(object)
    #: Minimum delay in milli seconds before reconnect is attempted.
    DELAY_MIN_MS = 100
    #: Maximum delay in milli seconds before reconnect is attempted.
    DELAY_MAX_MS = 1000 * 60 * 5

    def __init(self):
           #: Reconnect delay in milli seconds.
            self.delay_ms = self.DELAY_MIN_MS
    def _reconnect(self):
        _logger.debug('Waiting %d ms before next '
                      'connection attempt.' % self.delay_ms)
        yield from asyncio.sleep(self.delay_ms / 1000)
        self.delay_ms = min(2 * self.delay_ms, self.DELAY_MAX_MS)
        yield from self._connect()
```
This worked fine, as far as I can tell.

In 3ce0dbd8f1b77cf4278fb024500ba64bd2b4ee08 this logic was changed.  The minimum reconnection delay is now 5 min (30000 ms) and there is no maximum.

```python
class Defaults(Singleton):
        ReconnectDelay = 1000 * 60 * 5

class AsyncModbusTcpClient(ModbusBaseClient):
    def __init__(self, 
                 reconnect_delay: int = Defaults.ReconnectDelay):
        self.delay_ms = self.params.reconnect_delay
    async def _reconnect(self):
        txt = f"Waiting {self.delay_ms} ms before next connection attempt."
        _logger.debug(txt)
        await asyncio.sleep(self.delay_ms / 1000)
        self.delay_ms = 2 * self.delay_ms
```

I do not see the purpose of such a change, as it makes reconnections take very very long.  Was it perhaps unintentional?  I believe the logic change should be reverted (while preserving the refactor).

**Comment by janiversen** [comment]
pull requests are welcome.

**Comment by alexrudd2** [comment]
workin' on it

**Comment by janiversen** [comment]
small PRs that each solve one problem is preferred to one big one
