### ISSUE TITLE
PyPI doesn't include python version

### ISSUE THREAD

**Issue by MatthewWest** [riptideio/pymodbus#126]
The [PyPI page](https://pypi.python.org/pypi/pymodbus) for the package doesn't state what version of Python it's compatible with. As a result, `sudo pip3 install pymodbus` fails as it's trying to install the old Python 2 version. It'd be great if we could get a python 3 package posted.

**Comment by barik** [comment]
Any updates on this? Should be simple to set Py Version to 2 on the PyPI page, and would solve a lot of confusion.

**Comment by dhoomakethu** [comment]
with pymodbus v1.3.0rc1 the package can be installed on both python2 and python3.
