### ISSUE TITLE
Modbus Register Reading

### ISSUE THREAD

**Issue by sameer546** [riptideio/pymodbus#131]
I have trying to read data in being sent from PLC to register address 40001,40002,40003..
But the response is None. When I used trial version of the third party software I'm getting the data in those registers. 
Why I'm not able to read the data stored in the registers through python code.
I used the following: (RTU Mode, Using RS232 Cable)
import pymodbus
from twisted.internet import reactor, protocol
from pymodbus.constants import Defaults
from pymodbus.client.sync import ModbusSerialClient as ModbusClient

import logging
logging.basicConfig()
log = logging.getLogger()
log.setLevel(logging.DEBUG)

client = ModbusClient(method='rtu', port='COM4', timeout=1)
client.connect()

rq = client.write_register(1, 10)
rr = client.read_holding_registers(40001,1)
print (rr)

The output is:
DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:getting transaction 1
DEBUG:pymodbus.transaction:Running transaction 2
DEBUG:pymodbus.transaction:getting transaction 2
None

Kindly help me out in reading the exact register address.

**Comment by rlshumat** [comment]
Have you checked your baudrate? The default baudrate that pymodbus uses is 19200: http://pymodbus.readthedocs.io/en/latest/library/constants.html

Most PLCs that I have connected to default to a slower baud rate such as 9600. 
Second, on the line rr = client.read_holding_registers(40001,1), if you are looking at register 1 you only need to address 1 and not 40001. ( rr = client.read_holding_registers(1,1)) (Also depending on your PLC, you may need to read address 0 depending on if the PLCs addressing starts at 0 or 1.)
