### ISSUE TITLE
Documentation On Writing Values to Registers

### ISSUE THREAD

**Issue by OptrixAU** [riptideio/pymodbus#136]
I'd love to see some additional documentation on how you're expected to write values to the datastore when writing a Modbus/TCP server.

Writing 16-bit int values is pretty straight-forward, but if I wanted to write a //float// or //double// into the buffer instead, the documentation is quite unclear on how you'd force the data into the appropriate structure, taking endianness into account. 

I'd imagine it comes up often enough that it's worth documenting.

**Comment by dhoomakethu** [comment]
I will see if the documentation could be updated, meanwhile you can refer [modbus-payload-examples](https://github.com/riptideio/pymodbus/blob/master/examples/common/modbus-payload.py)
