### ISSUE TITLE
Endianness of registers when decoding

### ISSUE THREAD

**Issue by ifjake** [riptideio/pymodbus#138]
My PLC device uses big-endian to store values, however this also means whenever a datatype has to be split across two registers, it will also use the second register first, the endianness is across all 4 bytes as a whole. Currently I'm trying to decode some 32-bit floats with the payload decoder, but I had to redefine the decode_32bit_float so that it grabbed the last two bytes first and then the second two.

It works, but is there a better way I should be doing this?

```
def _decode_32bit_float_rev(self):
        self._pointer += 4
        fstring = self._endian + 'f'
        handle = self._payload[self._pointer - 2:self._pointer]
        handle += self._payload[self._pointer - 4:self._pointer - 2]
        return unpack(fstring, handle)[0]

BinaryPayloadDecoder.decode_32bit_float = _decode_32bit_float_rev
```

**Comment by semyont** [comment]
The PLC registers could be swapped...you can use ModiconPayloadDecoder Example by bash
[pymodbus/examples/contrib/modicon-payload.py](url)

    `def decode_32bit_float(self, size=1):
        ''' Decodes a float from the buffer
        '''
        self._pointer += 4
        fstring = self._endian + 'f'
        handle = self._payload[self._pointer - 4:self._pointer]
        handle = handle[2:] + handle[:2]
        return unpack(fstring, handle)[0]
`
