### ISSUE TITLE
Access one bit in a unique data store

### ISSUE THREAD

**Issue by anrodlo** [riptideio/pymodbus#141]
From the Modbus data model  definiton in the Modbus application protocol specification (chapter 4.3), if a unique data block (or store) is shared for holding, input registers, coils and discrete inputs, it must be possible to reach the same data "via several MODBUS functions, either via a 16 bit access or via an access bit".
But when I try to do this with pymodbus, writing a single coil overwrites the whole 16 bit register. And reading 16 coils does not correspond with the first register but with 16 registers, showing True if != 0.

Am I doing something wrong?

Server:

    block = ModbusSequentialDataBlock(0x00, [0]*0xff)
    store = ModbusSlaveContext(di=block, co=block, hr=block, ir=block)
    context = ModbusServerContext(slaves=store, single=True)
    StartTcpServer(context, address=("192.168.12.118", 5020))

Client:

    >>> client = ModbusTcpClient(host='192.168.12.118', port=5020)
    >>> rr = client.read_coils(1, 16, unit=1)
    >>> rr.bits
    [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    >>> client.write_registers(address=1, values=[8])
    >>> rr = client.read_coils(1, 16, unit=1)
    >>> rr.bits
    [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    >>> client.write_registers(address=10, values=[3])
    >>> rr = client.read_coils(1, 16, unit=1)
    >>> rr.bits
    [True, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False]

**Comment by dhoomakethu** [comment]
Why are using <write_registers> to write to a coil, you should be using <write_coil> if you want to override a single coil and <write_coils> if you want to override multiple coils.
[write_coil](http://pymodbus-n.readthedocs.io/en/latest/library/client-common.html#pymodbus.client.common.ModbusClientMixin.write_coil)
[write_coils](http://pymodbus-n.readthedocs.io/en/latest/library/client-common.html#pymodbus.client.common.ModbusClientMixin.write_coils)
