### ISSUE TITLE
pymodbus3 1.0.0 on pypi?

### ISSUE THREAD

**Issue by barik** [riptideio/pymodbus#145]
If this is the authoritative pypi repository, can you update the package that is available at:
https://pypi.python.org/pypi/pymodbus3/1.0.0

I was about to report a bug, only to realize that this bug is only for the http://uzumaxy.github.io/pymodbus3/ build of the pypi package.

**Comment by dhoomakethu** [comment]
official pymodbus with python3 support is available on pypi (v1.3.0rc1)
