### ISSUE TITLE
Attributerror: NoneType object has no attribute function_code/bits 

### ISSUE THREAD

**Issue by suibaf** [riptideio/pymodbus#146]
Hi,
my app work fine on raspberry pi for hour and hour, then without no apparente reason it give me this error, it continue to work but occasionally it give me this error.
I know what is the error, but I don't understand why it work fine and then it give this error!
BR

**Comment by dhoomakethu** [comment]
should be fixed with pymodbu 1.3.1 , please reopen in case the issue still persists
