### ISSUE TITLE
Stop loop in ModbusSingleRequestHandler in server/sync.py

### ISSUE THREAD

**Issue by Nanahara** [riptideio/pymodbus#149]
Hello,

Why self.running in handle function of ModbusSingleRequestHandler is not set at False on except ? If I run a ModbusSerialServer in a separate thread I cannot stop properly. And I think that the loop in serve_forever function in ModbusSerialServer is useless.

What do you think about that ?

**Comment by dhoomakethu** [comment]
Please try the fix from the dev branch and let me know if you still face any problem

**Comment by Nanahara** [comment]
Hello,

I test your fix and it seems to work correctly.

Thank you,
Alexis

2017-08-04 7:08 GMT+02:00 dhoomakethu <notifications@github.com>:
