### ISSUE TITLE
Mismatch reply on RTU request

### ISSUE THREAD

**Issue by thesems** [riptideio/pymodbus#1509]
### Versions

- Python: 3.11
- OS: Ubuntu 22.04
- Pymodbus: 3.2.1
- Modbus Hardware (if used):

### Pymodbus Specific

- Server: rtu - async
- Client: rtu - async

### Description

I'm running two tasks in parallel, both reading holding registers. One is fast (every 0.25s) and the other one slower (every 3s).
Most of the time everything works, but occasionally the size passed in the read is not matching the returned size. Instead the size matches the read request from the other task. So it means the read is returning the reply for another request. 

As shown in the code below, sometimes read_block_1_fast() receives the reply for read_block_2_slow().
I'm using the AsyncModbusSerialClient class to create a client with default settings with following changes: baud-rate 115200, timeout 1s.

I noticed the transaction id always equals to the slave id. Why is this the case and is it the source of the error? Does it mean I should use some kind of queue to ensure order?

### Code and Logs

```python

group.create_task(self.read_block_1_fast())
group.create_task(self.read_block_2_slow())
```

Each function looks roughly like this:
```python
def read_block_1_fast():
  while True:
      await asyncio.sleep(0.25)  # other function has 3
  
      try:
          results = await self.read_holding_registers(address, size, unit)
      except (ModbusException, asyncio.TimeoutError):
          continue
  
      if len(results) != size:
          # this gets sometimes triggered
          logger().debug(
              f"Modbus response mismatch: {results} with size {len(results)} is not size {size}"
          )
          continue
      
      self.results  = results
```

**Comment by janiversen** [comment]
You need to add a lock, to ensure that you do not execute 2 requests at the same time. The calls are not threadsafe

**Comment by janiversen** [comment]
yes forgot that, that is because modbus serial do not have a transaction id, so we simulate it.
