### ISSUE TITLE
Publish pymodbus on pypi

### ISSUE THREAD

**Issue by andrey-git** [riptideio/pymodbus#155]
Could you publish this package on Pypi, so it can be fetched without specifying the github URL?

home-assistant/home-assistant#7069

Thanks!

**Comment by DaveTrussel** [comment]
+1 Or is there a reason only the python 2 version is on PyPI?

**Comment by dhoomakethu** [comment]
pymodbus is already available in PyPi.
[PyModbus](https://pypi.python.org/pypi/pymodbus)

**Comment by andrey-git** [comment]
@dhoomakethu That pypi version is 4 years old. Does it support python3?

**Comment by dhoomakethu** [comment]
Ah, you are talking about python3, no there is not one on the pypi, you could try this branch .[python3](https://github.com/riptideio/pymodbus/tree/python3) , I will see if there is a version made available for python3 , but I do not have a ready timeline.

**Comment by MartinBorg** [comment]
It would be nice to have **one** pymodbus for both 2.7 and 3.4+ at some point.
Are there any plans for a merge?

**Comment by dhoomakethu** [comment]
I am currently working on it, I do not have a definite timeline though.

**Comment by dhoomakethu** [comment]
A new universal version is now available on pypi

**Comment by jonadem** [comment]
It should be nice to state clearly in the package 'pymodbus3' on pypi that 'pymodbus' should be used instead.
https://pypi.org/project/pymodbus3/
