### ISSUE TITLE
'WriteMultipleRegistersResponse' object has no attribute 'registers'

### ISSUE THREAD

**Issue by oryxr** [riptideio/pymodbus#165]
I use RTU serial sync communication with pymodbus on master .
It works perfectly but sometime this error occur :
`ModbusExceptionError with 'writeCoils': IllegalValue
` and after I have this errors recurrents : `'WriteMultipleRegistersResponse' object has no attribute 'registers'` or this error too:
`'WriteMultipleCoilsResponse' object has no attribute 'bits'`
I can't repeat error, but when I restart code (master or slave) the error disappear
What do you think
Thanks and sorry for my poor english

**Comment by oryxr** [comment]
I this error too, same condition:
`'WriteMultipleCoilsResponse' object has no attribute 'bits':`

**Comment by dhoomakethu** [comment]
what version of pymodbus are you working with ?

**Comment by oryxr** [comment]
pymodbus 1.2.0 branch python3, same error with python2

**Comment by dhoomakethu** [comment]
Please use the latest v 1.3.0rc1 , it is supposed to have a bug fix for similar problem. Let me know your findings

**Comment by oryxr** [comment]
I test with the new version and I have the same error

**Comment by oryxr** [comment]
always this errors with rc2

**Comment by dhoomakethu** [comment]
Are you trying this against any real modbus device ? Can you give some more information regarding your setup and baudrate?
