### ISSUE TITLE
ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by oryxr** [riptideio/pymodbus#170]
When I run pymodbus-1.3.0-rc1 with debug activate, I have this error:
`ord() expected string of length 1, but int found`

I remove ord function in transaction.py and sync.py same as:
`# _logger.warning("cleanup recv buffer before send: " + " ".join([hex(ord(x)) for x in result]))`
to
`_logger.warning("cleanup recv buffer before send: " + " ".join([hex(x) for x in result]))`

and it run.
Why do you add the ord() ?

**Comment by dhoomakethu** [comment]
what version of python are you using ? Could you provide the code snippet, which is causing you this error ?

**Comment by dhoomakethu** [comment]
If you are using python3, there is a bugfix on the way.

**Comment by oryxr** [comment]
I using python3 and when I remove only ord( it's run correctly)

**Comment by dhoomakethu** [comment]
A version with the fix will be available by this week.
