### ISSUE TITLE
struct.error: argument for 's' must be a bytes object

### ISSUE THREAD

**Issue by Lstick** [riptideio/pymodbus#171]
When I run pymodbus-1.3.0-rc2 with debug activate, I have this error:

>   builder.add_string('abcdefgh')
>   File "/usr/lib64/python3.4/site-packages/pymodbus-1.3.0rc2-py3.4.egg/pymodbus/payload.py", line 179, in add_string
> struct.error: argument for 's' must be a bytes object

Code is:
builder = BinaryPayloadBuilder(endian=Endian.Little)

builder.add_string('abcdefgh')

payload = builder.build()

**Comment by dhoomakethu** [comment]
if you are using python3 , pass the string as bytestring , 
`builder.add_string(b'abcdefgh')`

**Comment by Lstick** [comment]
Thanks a lot!
