### ISSUE TITLE
How to change the baud rate?

### ISSUE THREAD

**Issue by chendrix4** [riptideio/pymodbus#182]
I have the most recent version of pyModbus and am running in Python 3. I don't see any way to change the Modbus parameter. I installed the module with pip and have thoroughly examined the source code.

**Comment by dhoomakethu** [comment]
You can  basically pass any of the serial parameters while creating the serial client. Just pass the desired parameter as a keyword argument.
[serial](https://pythonhosted.org/pyserial/pyserial_api.html#serial.Serial)

Example
```
from pymodbus.client.sync import ModbusSerialClient as ModbusClient
client = ModbusClient(method='rtu', port='/dev/ttyp0', timeout=1, baudrate=19200)
```
