### ISSUE TITLE
`close()` Coroutine not awaited when using TCP

### ISSUE THREAD

**Issue by wlockwood** [riptideio/pymodbus#1892]
### Versions

- Python: 3.11.1
- OS: Windows 11
- Pymodbus: 3.5.4
- Modbus Hardware: Dent Instruments HD3

### Pymodbus Specific
Async client

### Description
(May be a regression bug related to #1365)
The context managed implementation for `AsyncModbusTcpClient` doesn't await `close()`.

I tested this with the example code from the [ReadTheDocs](https://pymodbus.readthedocs.io/en/latest/source/client.html#client-usage) and a context-managed clone of the same.

#### Context managed
```python
import asyncio
from pymodbus.client import AsyncModbusTcpClient

async def main():
    test_host: str = "my_test_ip"

    client = AsyncModbusTcpClient(test_host)  # Create client object
    with AsyncModbusTcpClient(host=test_host) as client:
        await client.connect()  # connect to device, reconnect automatically
        result = await client.read_coils(2, 3, slave=1)  # get information from device
        print(result.bits[0])  # use information

if __name__ == "__main__":
    asyncio.run(main(), debug=True)
```
Results in:
```
client\base.py:368: RuntimeWarning: coroutine 'AsyncModbusTcpClient.close' was never awaited
client\base.py", line 368, in __exit__
```
#### Manual
Opening and closing the client manually works and doesn't encounter any exceptions:
```python
import asyncio
from pymodbus.client import AsyncModbusTcpClient

async def main():
    test_host: str = "my_test_ip"
    client = AsyncModbusTcpClient(test_host)  # Create client object
    await client.connect()  # connect to device, reconnect automatically
    result = await client.read_coils(2, 3, slave=1)  # get information from device
    print(result.bits[0])  # use information

if __name__ == "__main__":
    asyncio.run(main(), debug=True)
```

**Comment by janiversen** [comment]
It could be a regression, but in your manual example you forgot to call close()

**Comment by janiversen** [comment]
to be honest you are not the only one, I thought there was a problem in the library, but looking at your code again, I can see it.

Let us hear if you stumble on other problem
