### ISSUE TITLE
twisted port.stopListening() doesn't stop?

### ISSUE THREAD

**Issue by karlp** [riptideio/pymodbus#19]
I'm building a small gtk3 (pygobject) app, and I want to start/stop the modbus server socket (this is a modbus server, faking out the real hardware)

in my gtk main window, I have this...

```
from pymodbus.server.async import ModbusServerFactory
self.context = ModbusServerContext(slaves=slaves, single=False)
framer  = ModbusSocketFramer
self.factory = ModbusServerFactory(self.context, framer)
```

and on the button press...

```
self.mb_port = reactor.listenTCP(1502, self.factory, interface="0.0.0.0")
```

This works well, but for the "stop" button, simply calling

```
self.mb_port.stopListening() #doesn't do anything.
```

I know this might be deferred, but I don't see it ever finish.  There is a client continually making modbus requests, but I still expected this to stop eventually.  Am I doing something wrong?

**Comment by estan** [comment]
Not sure if the problem I have is similar, but I'm using a `ModbusTcpServer` upon which I call `serve_forever` in a thread. But trying to shut down the server by calling `shutdown` is not working. The `shutdown` call blocks seemingly forever (and the server keeps serving requests).

This only happens when a client is continually making requests. If there's no traffic, then the `shutdown` call succeeds and returns and the server stops.

Not sure if it's related...

**Comment by estan** [comment]
To clarify. I'm using Qt, and I set up the server and call `serve_forever` as follows:

```python
class IOSimulatorThread(QThread):
    """Simulator thread."""

    changed = pyqtSignal()

    def __init__(self, host, port, parent=None):
        QThread.__init__(self, parent)

        # Create data blocks.
        self.inputs = InputDataBlock()
        self.outputs = OutputDataBlock()

        # Create slave and server contexts.
        slave = ModbusSlaveContext(hr=self.outputs, ir=self.inputs)
        context = ModbusServerContext(slaves=slave)

        # Create Modbus server.
        self.server = ModbusTcpServer(context, ModbusSocketFramer, None, (host, port))

    def run(self):
        self.server.serve_forever()

    def stop(self):
        self.server.shutdown()
```

I create and start such a thread in my GUI code, and when my main window closes, I do:

```python
    def closeEvent(self, event):
        if self.thread.isRunning():
            self.thread.stop()
            if not self.thread.wait(msecs=500):
                print('Terminating...')
                self.thread.terminate()
```

But the program never terminates if there are clients actively making requests. The `shutdown` call never returns.

**Comment by dhoomakethu** [comment]
cleaning up old issues.
