### ISSUE TITLE
Fix examples 

### ISSUE THREAD

**Issue by dhoomakethu** [riptideio/pymodbus#190]

**Comment by tryer3000** [comment]
`examples/functional/synchronous-rtu-client.py` fail to pass on ubuntu 16.04

**Comment by dhoomakethu** [comment]
@tryer3000 could you please paste the error trace here ?

**Comment by tryer3000** [comment]
@dhoomakethu  FYI

EEEEEE
======================================================================
ERROR: testReadWriteCoil (__main__.SynchronousRtuClient)
----------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/home/joshua/ws/open/pymodbus/examples/functional/base_runner.py", line 33, in testReadWriteCoil
    self.__validate(rq, lambda r: r.function_code < 0x80)
  File "/home/joshua/ws/open/pymodbus/examples/functional/base_runner.py", line 81, in __validate
    else: self.assertTrue(test(result))
  File "/home/joshua/ws/open/pymodbus/examples/functional/base_runner.py", line 33, in <lambda>
    self.__validate(rq, lambda r: r.function_code < 0x80)
AttributeError: 'ModbusIOException' object has no attribute 'function_code'
```

**Comment by dhoomakethu** [comment]
Thanks, will have a look

**Comment by rahulraghu94** [comment]
@dhoomakethu, are there more examples that are broken apart from the ones that got fixed this week?
