### ISSUE TITLE
[ModbusSerialClient] On higher baudrates _silent_interval is too small to be enforced

### ISSUE THREAD

**Issue by vermut** [riptideio/pymodbus#191]
At least say if I'm right or wrong.

Code at: https://github.com/riptideio/pymodbus/blob/master/pymodbus/client/sync.py#L367

Baudrate: 57600
`_silent_interval`: 0.000668402777778
typical `ts`: 1499640168.84
typical `_last_frame_end`: 1499640168.83

It appears quite often `ts == self._last_frame_end + self._silent_interval` due to float round error. Even if it's 0.00001 smaller.

**Comment by vermut** [comment]
P.S. I'm not sure if `time.sleep(0.000668402777778)` will do something meaningful instead of being rounded up to 0.

**Comment by dhoomakethu** [comment]
I agree , its been on my plate for sometime.
`// Modbus states that a baud rate higher than 19200 must use a fixed 750 us 
// for inter character time out and 1.75 ms for a frame delay.
// For baud rates below 19200 the timeing is more critical and has to be calculated.
// E.g. 9600 baud in a 10 bit packet is 960 characters per second
// In milliseconds this will be 960characters per 1000ms. So for 1 character
// 1000ms/960characters is 1.04167ms per character and finaly modbus states an
// intercharacter must be 1.5T or 1.5 times longer than a normal character and thus
// 1.5T = 1.04167ms * 1.5 = 1.5625ms. A frame delay is 3.5T.    

if (baud > 19200)
{
    T1_5 = 750; 
    T3_5 = 1750; 
}
else 
{
    T1_5 = 15000000/baud; 
    T3_5 = 35000000/baud; 
}`

**Comment by dhoomakethu** [comment]
Thats a good thing to have but not a high priority item to be considered for development. Though the timings on python is not guaranteed, it should work for most of the cases considering the fact that majority of the hardwares/OS combination on which pymodbus is being run is good.

**Comment by xtofl** [comment]
Ok.  Thanks for the quick reply!

**Comment by dhoomakethu** [comment]
fixed with 1.3.2
