### ISSUE TITLE
Problem with read_coils and read_discrete_inputs

### ISSUE THREAD

**Issue by marokamaro** [riptideio/pymodbus#194]
Hello,

I made a slave with a register with 8 bits (I tried also many different variants - it is only an example):

```
builder_coils = BinaryPayloadBuilder(endian=Endian.Big)
builder_coils.add_bits([1,0,1,0,1,0,1,0])
co_block = ModbusSequentialDataBlock(0, builder_coils.build())
slaves = {
    0x01: ModbusSlaveContext(co=slave1.co_block, zero_mode=True),
    }
context = ModbusServerContext(slaves=slaves, single=True)
```

And when I try to read this register in ModbusMaster I always receive 0101 as an answer:

> 
> DEBUG:pymodbus.server.sync:0x1 0x1 0x0 0x0 0x0 0x1 0xfd 0xca
> DEBUG:pymodbus.factory:Factory Request[1]
> DEBUG:pymodbus.datastore.context:validate[1] 0:1
> DEBUG:pymodbus.datastore.context:getValues[1] 0:1
> DEBUG:pymodbus.server.sync:send: 010101019048

I tried to decode this with this code:

```
result = client.ReadCoilsRequest(0,1, unit=0x01)
decoder = BinaryPayloadDecoder.fromCoils(result.bits, endian=Endian.Big)
decoded = { 'bit': result.bits[0]}

print "-" * 60
print "Decoded Data"
print "-" * 60
for name, value in decoded.iteritems():
    print ("%s\t" % name), value
```

but I received:

> ------------------------------------------------------------
> Decoded Data
> ------------------------------------------------------------
> bit	[True, False, False, False, False, False, False, False]

I don't have any problems with holding or input registers

Is there any mistake or there is a fault in pymodbus library?

**Comment by dhoomakethu** [comment]
use `to_registers()` instead of `build()` , `build()` does not take care of the endianess, `to_registers()` considers the endianness before calling building the payload.

`co_block = ModbusSequentialDataBlock(0, builder_coils.to_registers())`
