### ISSUE TITLE
client get the value is not expected,please check.

### ISSUE THREAD

**Issue by allon3721** [riptideio/pymodbus#197]
store = ModbusSlaveContext(
    di = ModbusSequentialDataBlock(0, [(x if x % 2 != 0 else 0) for x in xrange(2000)]),
    co = ModbusSequentialDataBlock(0, [(x if x % 2 != 0 else 0) for x in xrange(2000)]),#[0, 1, 0, 3, 0, 5...
    hr = ModbusSequentialDataBlock(0, [(x+1) for x in xrange(125)]),
    ir = ModbusSequentialDataBlock(0, [(x+1) for x in xrange(125)]))
print 'ir list:',store.store['i']
context = ModbusServerContext(slaves=store, single=True)

DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x2 0x0 0x1 0x0 0x8
DEBUG:pymodbus.transaction:recv: 0x0 0x1 0x0 0x0 0x0 0x4 0x0 0x2 0x1 0x55
DEBUG:pymodbus.transaction:0x0 0x1 0x0 0x0 0x0 0x4 0x0 0x2 0x1 0x55

function code is 0x4. getvalues for address 0,quatity 8. the result is 0x55.i think result should be 0xaa. pls check is bug or not.

**Comment by dhoomakethu** [comment]
Please use zero_mode.
```
# The slave context can also be initialized in zero_mode which means that a
# request to address(0-7) will map to the address (0-7). The default is
# False which is based on section 4.4 of the specification, so address(0-7)
# will map to (1-8)::
#
#     store = ModbusSlaveContext(..., zero_mode=True)
```
