### ISSUE TITLE
problem for getValues method.

### ISSUE THREAD

**Issue by allon3721** [riptideio/pymodbus#198]
def getValues(self, fx, address, count=1):
        ''' Validates the request to make sure it is in range

        :param fx: The function we are working with
        :param address: The starting address
        :param count: The number of values to retrieve
        :returns: The requested values from a:a+c
        '''
        address = address + 1  # section 4.4 of specification
        _logger.debug("getValues[%d] %d:%d" % (fx, address, count))
        return self.__get_callbacks[self.decode(fx)](address, count)

address = address + 1, tell me why address add 1?value got is incorrect, For example, invoke read holding register method,input parameter: address 0, quantity 1. value return now is from address 1,not from address 0.

**Comment by dhoomakethu** [comment]
please refer # section 4.4 of specification from [Modbus Protocol Spec](http://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf )
