### ISSUE TITLE
Finish Adding Functional Tests

### ISSUE THREAD

**Issue by bashwork** [riptideio/pymodbus#2]
Finish adding the functional tests for all the server code and finish the unit test for the remainder of the server/client code.

Make sure that we are also using correct reference implementations (jamod, modpoll, etc) for each test:
- sync/async server
- sync/async client
- special contexts

**Comment by janiversen** [comment]
Closing this for now.

We have to rework the whole test scenario, since it has grown a bit chaotic to say the least.
