### ISSUE TITLE
example code bug in remote_server_context.py

### ISSUE THREAD

**Issue by MarekLew** [riptideio/pymodbus#234]
In file: 
https://github.com/riptideio/pymodbus/blob/master/examples/contrib/remote_server_context.py#L160

`RemoteServerContext` not have `self.__slaves`

more in:
https://github.com/riptideio/pymodbus/commit/fec7ac37f37e3d29196f6775c24a833bf9881539

**Comment by dhoomakethu** [comment]
There you go, #4736b0f , Thats just an example and not a part of main library. Please feel free to do the changes and raise PR. The changes for `__iter__` is done inline with python 3 compatibility. I am closing this issue. Please comment on the PR, if you have further concerns.
