### ISSUE TITLE
pymodbus.client.sync import ModbusTcpClient -error

### ISSUE THREAD

**Issue by rickmoua** [riptideio/pymodbus#244]
### Versions

* Python: v3.6
* OS: win 10
* Pymodbus:
* Modbus Hardware (if used):  SICK Lector

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
 # code and logs here.

```

I tried to run the command "pymodbus.client.sync import ModbusTcpClient"
but getting this error below.

I already download the pymodbus from github and install it. But when run the command get the below error.

>>> from pymodbus.client.sync import ModbusTcpClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pymodbus'

**Comment by dhoomakethu** [comment]
Make sure pymodbus is in the `PYTHONPATH`.
