### ISSUE TITLE
Seems impossible to create a MODBUS/TCP server on port 502

### ISSUE THREAD

**Issue by ltcasg** [riptideio/pymodbus#247]
Hello

Using pymodbus 1.3.2 on a Raspberry Pi 3 with Raspbian and Python 2.7 installed, I tried to create a MODBUS/TCP server from the "Synchronous Server Example"

To be able to communicate with a MODBUS/TCP client I replaced the line:
```python,
StartTcpServer(context, identity=identity, address=("localhost", 5020))
```
with
```python
StartTcpServer(context, identity=identity, address=("192.168.0.42", 502))
```
But unfortunately, launching the modified script generates a "Permission denied" error in socket.py.

If I replace 502 with 5020, the server is functionnal and responds correctly

Is it a known issue in pymodbus, python 2.7 socket.py, ...  ?

Thanks

**Comment by dhoomakethu** [comment]
Run as sudo

**Comment by ltcasg** [comment]
Thanks for your answer

But it seems I have another issue when I try to use ```sido```
![image](https://user-images.githubusercontent.com/34121979/33430707-c7d05e0a-d5d1-11e7-8584-996b50bfbb01.png)

**Comment by dhoomakethu** [comment]
You probably need to set the `PYTHONPATH` ,so that the python interpreter can find the installed pymodbus package.

**Comment by ltcasg** [comment]
For all having the same issue as mine, here is the way I used to solve it:

In the server script, initialize the server with its IP address and a port > 1024
```
StartTcpServer(context, identity=identity, address=("192.168.0.42", 502))
```

open a LXTerminal window and execute:
```
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 502 -j REDIRECT --to-port 5020
```
then launch the server script.

Test with a MODBUS/TCP client and result on wireshark
![image](https://user-images.githubusercontent.com/34121979/33702863-bdb645de-db25-11e7-91f6-3112e80fb94a.png)

Server responds correctly and Wireshark is able to recognize MODBUS frames as port 502 is used!
