### ISSUE TITLE
PEP-8 Compliant code

### ISSUE THREAD

**Issue by dhoomakethu** [riptideio/pymodbus#257]
Make Pymodbus PEP-8 compliant

**Comment by rahulraghu94** [comment]
Yikes. This going to take a while :P

**Comment by swamper123** [comment]
What can be done is throwing [black](https://black.readthedocs.io/en/stable/) on it (but pls. with 120 chars per line, unless you realy want that stuff shall looks nice on the terminal), see what stuff was changed (and if tests are still running fine) and merge a PR.
Then add flake8 tests on the Github Actions, kick all PRs again in Github Actions and newer tests have to pass it as well.

**Comment by swamper123** [comment]
In the same breath we may add sth. that the coverage will not drop and contributers are forced to add tests for new PRs.

**Comment by janiversen** [comment]
This is now solved with 3.0.0dev4.
