### ISSUE TITLE
TypeError: __init___() got an unexpected keyword argument 'endian'

### ISSUE THREAD

**Issue by josemariasecurity** [riptideio/pymodbus#271]
Hi!

Firstly, congratulations for your work. Sorry, I have this error when I use your code. I attach an image with the error: http://es.tinypic.com/view.php?pic=2925oht&s=9

Thank you. Regards.

**Comment by rahulraghu94** [comment]
@josemariasecurity, `BinaryPayloadBuilder` takes arguments `payload`, `byteorder` and `wordorder`.
Endian as an argument is no longer supported!

Eg:
`>>> builder = BinaryPayloadBuilder(byteorder=Endian.Little)`


Do let us know if you face any other problems
