### ISSUE TITLE
write_registers() stalls when using serial

### ISSUE THREAD

**Issue by BitBoxLtd** [riptideio/pymodbus#273]
write_registers() stalls when using serial.

Log shows that read was waiting for 1024 bytes of response but received 8.
Copying get_response_pdu_size() method from WriteSingleRegisterRequest class to WriteMultipleRegistersRequest class appears to fix it.

Python v3.4.4
pymodbus v1.4.0
pyserial v3.4

**Comment by rahulraghu94** [comment]
Could you please raise a pull request against dev branch if you have a fix?

**Comment by BitBoxLtd** [comment]
This is a duplicate of #267 - closing.
