### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yegorich** [riptideio/pymodbus#279]
What type of BSD this project is licensed to? There are more than 10 different versions of BSD license featured on [SPDX](https://spdx.org/licenses/). A license file would be also appreciated.

**Comment by dhoomakethu** [comment]
We do have a license file(hidden under doc) [License](https://github.com/riptideio/pymodbus/blob/master/doc/LICENSE)

**Comment by yegorich** [comment]
OK. I see now. Seems to be BSD-3-Clause. Thanks.
