### ISSUE TITLE
Problem with chunked response via TCP/IP server

### ISSUE THREAD

**Issue by Edke** [riptideio/pymodbus#28]
Hello again.

While testing #21 my code reminded me, that I had to rewrite ModbusTcpClient because my [Planet ICS-100 Media converter](http://www.planet.com.tw/en/product/product.php?id=16529) returns response from Modbus device not as single packet, but data are chunked across multiple packets.

I have rewritten ModbusTcpClient, please inspect this [code](https://gist.github.com/Edke/6007273) and tell me your opinion. Also here is [wireshark session](https://www.dropbox.com/s/tjb8cjvcxdigvrb/chunked_response.pcapng) so you can inspect packets for yourself.

**Comment by roberthdevries** [comment]
There is a small typo on line 150 of transaction.py

Here is the patch:
diff --git a/pymodbus/transaction.py b/pymodbus/transaction.py
index 4000f65..b2040c3 100644
--- a/pymodbus/transaction.py
+++ b/pymodbus/transaction.py
@@ -147,7 +147,7 @@ class ModbusTransactionManager(object):
             # the current frame and alert the application code
             # that there was an error.
             elif self.state == FramerState.ErrorInFrame:
-                _logger.debug("entering error state: %d:%s", len(self.framer._buffer, self.framer._header))
+                _logger.debug("entering error state: %d:%s", len(self.framer._buffer), self.framer._header)
                 self.framer.resetFrame()
                 return False

**Comment by bashwork** [comment]
Ah, good find. I'll patch this asap.

**Comment by dhoomakethu** [comment]
This should be fixed with pymodbus v1.5.0 and above (sync client)
