### ISSUE TITLE
cannot enable/disable RTS for client and slave

### ISSUE THREAD

**Issue by ghost** [riptideio/pymodbus#33]
when  i use serial RTU and RS-485  wires, how do i set set RTS high and low.

i know i gotta to do it in the source codes, like for read_holding_register request , i need to set it high to send the request and low to receive the response from slave.

and for the slave Linux box, i need to set RTS high to send a reponse back to master and set it low right after that. 

where do i do that ? 

i know i can setRTS using pyserial.

**Comment by dhoomakethu** [comment]
closing stale issue

**Comment by mjm987** [comment]
I know this is is old thread but following works for me like a charm by ..
a) overloading ModbusSerialClient  and 
b) calculate the correct RTS delay time

`class MyModbusSerialClient(ModbusSerialClient):
  def __init__(self, **args):
    super(MyModbusSerialClient, self).__init__(**args)

  def _send(self, request):
    if not self.socket:
        raise ConnectionException(self.__str__())
    if request:
        print("in _send")
        txtime = (len(request)+1) * (10.0 / self.baudrate)
        self.socket.setRTS(False)
        time.sleep(0.001)
        rc = self.socket.write(request)
        time.sleep(txtime)
        self.socket.setRTS(True)
        return rc
    return 0

client = MyModbusSerialClient(method='rtu', port='/dev/ttyUSB0', baudrate=4800)
...

`
