### ISSUE TITLE
`client.async` sneaking in dependencies

### ISSUE THREAD

**Issue by patrickfuller** [riptideio/pymodbus#338]
In importing `client.async.asyncio`, `client.async.__init__` triggers `from pymodbus.client.async.deprecated.async` ([source](https://github.com/riptideio/pymodbus/blob/master/pymodbus/client/async/__init__.py)), which then imports twisted. Twisted is a fairly heavy dependency and is not needed to use asyncio.

**Comment by dhoomakethu** [comment]
@patrickfuller please give a try with branch https://github.com/riptideio/pymodbus/tree/sneaky-twisted and let me know if that solves this issue. Thanks.

**Comment by patrickfuller** [comment]
This fix works for me. Thanks!

**Comment by dhoomakethu** [comment]
Thanks for the confirmation. I will merge the PR in to `dev`.

**Comment by ralienpp** [comment]
I work in an environment where we use a Python interpreter for various processes. Although `twisted` is present, the process that uses `pymodbus` relies exclusively on `asyncio`, so the solution from https://github.com/riptideio/pymodbus/pull/339 is not suitable for our case.

A note for others digging around this area - I monkey-patched `is_installed` with a function that always returns False, to ensure that an attempt to load `twisted` will not occur:

```
def my_is_installed(_): return False
pymodbus.compat.is_installed = my_is_installed
```

**Comment by dhoomakethu** [comment]
If there's a possibility use virtualenvs to avoid these kinds of problems and workaround
