### ISSUE TITLE
pymodbus read_input_status

### ISSUE THREAD

**Issue by NagarjunaReddy1242** [riptideio/pymodbus#352]
Hi sir,
I got one error passing this parameter.
result= client.read_input_status(0x002E,0x003,unit=0x01)

o/p:  result=client.read_input_status(0x002E,3,unit=0x01)
AttributeError: 'ModbusSerialClient' object has no attribute 'read_input_status'

**Comment by dhoomakethu** [comment]
There is no method called `read_input_status` in modbus client, You probably are trying to use `read_discrete_inputs` or `read_input_registers`.
