### ISSUE TITLE
Is there any way to Convert the type of value we are getting from read_holding_registers?

### ISSUE THREAD

**Issue by arslion** [riptideio/pymodbus#381]
I am getting the data using Read holding registers. All is working fine.
Also I am getting data using Modbus Poll on Windows.
I am getting same values when I choose signed in Display. But I want to get the value which is in Float Inverse.
![image](https://user-images.githubusercontent.com/3967627/51767971-b3b1c780-2100-11e9-8c5b-efea9ce51729.png)

How can I achieve this using pymodbus?

### Versions

* Python: 2.7
* OS: ubilinux
* Pymodbus: 2.1.0
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
 # code and logs here.

```

**Comment by tracernz** [comment]
PyModbus includes the BinaryPayloadDecoder class:
https://pymodbus.readthedocs.io/en/latest/source/library/pymodbus.html#pymodbus.payload.BinaryPayloadDecoder
https://pymodbus.readthedocs.io/en/latest/source/example/modbus_payload.html

Alternately you can just use python's struct module to pack the 16-bit register values to bytes, then unpack in the format of your choice.

**Comment by arslion** [comment]
How can I get Float Inverse value using struct?
![GitHawk Upload by arslion](https://i.imgur.com/Xhh5gs1.jpg)

`unpack(‘f’,pack(‘hh’,value1,value2))`

Let me know what to use here instead of `f` and `hh`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tracernz** [comment]
I think you need to swap the registers, at least according to what I could find on "float inverse" [0].
```python
struct.unpack('f', struct.pack('HH', value2, value1))
```

[0] Section 4.4.4 https://www.walchem.com/literature/Controllers/WM/180413_WIND%20Modbus%20Manual.pdf

**Comment by dhoomakethu** [comment]
You can use `BinaryPayloadDecoder` where in you can specify the`byteorder` and `wordorder` as well. refer comments in this [example](https://github.com/riptideio/pymodbus/blob/master/examples/common/modbus_payload.py)

**Comment by dhoomakethu** [comment]
@arslion I will be closing this issue. Please feel free to reopen in case you have not found what you were looking for.

**Comment by arslion** [comment]
`struct.unpack('>f', struct.pack('>HH', value2, value1))`
I got the value by doing this. You got to use big-endian of little endian depending on OS. Also you need to pack inside unpack. Somehow its not working if I pack in another variable and pass it in unpack.

for details depending on what others are using check this link: [Python 2](https://docs.python.org/3/library/struct.html) [Python 3](https://docs.python.org/3/library/struct.html)

Thanks everyone specially @tracernz 👍
