### ISSUE TITLE
Reconsider use of time.time() function

### ISSUE THREAD

**Issue by wrobell** [riptideio/pymodbus#386]
Going through the code, I can see that `time.time` function is used in few places - to calculate timeouts mostly. The time returned by this function can be adjusted (i.e. what will happens to 30s timeout scheduled just before an user or NTP client changed the time?). IMHO, it would be better to switch to use of `time.monotonic`.

EDIT: Originally, I have stated that `time.time` can be affected by DST change. That's not true. Changed the example in the description above.

**Comment by dhoomakethu** [comment]
That's a good suggestion, I will make a note. Thanks
