### ISSUE TITLE
Module named async which is a reserverd word in python3.

### ISSUE THREAD

**Issue by AtibaBryan** [riptideio/pymodbus#391]
The module for making asynchronous communication over modbus is named `async` which is a reserved word in python3. This is making importing the async module in python3 code difficult to impossible.

I propose renaming the module, but I know that would be a breaking change.
Does anybody know of a work around for the time being?

**Comment by dhoomakethu** [comment]
The support is part of 2.2.0 release (available via PIP as well as a release canidate `pip install pymodbus==2.2.0rc3`
