### ISSUE TITLE
Distribute License with Source

### ISSUE THREAD

**Issue by cdgarren** [riptideio/pymodbus#401]
Should the license be distributed with the source tarball? I'm trying to create a yocto recipe to use this and it generally expects there to be a license file, but the download from pypi does not have it included.

**Comment by dhoomakethu** [comment]
[LICENSE](https://github.com/riptideio/pymodbus/blob/master/doc/LICENSE) is part of the doc folder. You can modify the recipe to fetch it from there.

**Comment by cdgarren** [comment]
I understand that it's part of the doc folder. However, yocto recipes can easily pull from pypi, and your distribution there does NOT include the License file.

**Comment by dhoomakethu** [comment]
Got it, I will make sure it is available as part of pypi in future releases. Thanks

**Comment by ffontaine** [comment]
It seems that latest release (2.3.0rc1) on pypi doesn't contain the license file. It would be really nice to add it on next release.

**Comment by dhoomakethu** [comment]
@ffontaine @cdgarren Please check v2.3.0. The license should be part of the source distribution now.
