### ISSUE TITLE
Use pycryptodome instead of pycrypto.

### ISSUE THREAD

**Issue by lalit-lintel** [riptideio/pymodbus#402]
### Versions

* Python: 2.7.12
* OS: Ubuntu 18.04
* Pymodbus: 2.1.0 [twisted]
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp - async

### Description

I am trying to use Mod bus server on TCP protocol, but when I installed pymodbus and I saw it's installed pycrypto, which is deprecated and dead software. 

I already have installed pycryptodome in my application, which is a conflict with pycrypto, 
we can't have both pycrypto and pycryptodome at the same time,

Can we have pymodbus[twisted] release which can use pycryptodome instead of pycrypto?

**Comment by dhoomakethu** [comment]
I am not sure of the amount of effort this might need, I would be glad to accept a PR if you can give a try with pycryptodome and can assure nothing breaks.

**Comment by tracernz** [comment]
AFAICT twisted doesn't use PyCrypto? https://github.com/twisted/twisted/pull/953

**Comment by lalit-lintel** [comment]
Added pull request with changes in the setup file, which will allow installing Cryptodome instead Crypto.

Pull request #409
