### ISSUE TITLE
Modbus garbage values in return and error AttributeError: 'ExceptionResponse' object has no attribute 'registers'

### ISSUE THREAD

**Issue by mksharma** [riptideio/pymodbus#41]
Hi Guys,
My modbus system is Asynchronous and  I have tried to solve my problem in 2 ways

Way 1: I am trying to read a register in this way:
# 

1.self.client = ModbusClient(ip_add)
2.result  = self.client.read_holding_registers(register_start_add,num_of_registers)
3.decoder = BinaryPayloadDecoder.fromRegisters(result.registers, endian=Endian.Little)
4.
5. if format_of_reg == 'ASCII': output = decoder.decode_string(num_of_registers)
6. if format_of_reg == 'REAL': output = decoder.decode_32bit_float()
7. if format_of_reg == 'UDINT': output = decoder..decode_16bit_uint()
8. if format_of_reg == 'INT': output = decoder.decode_8bit_int()
9. if format_of_reg == 'UINT': output = decoder.decode_8bit_uint()
10.if format_of_reg== 'bits': output = decoder.decode_bits()
11.
12. print str(output)
# 

I am getting correct output  contained in the register but for only those registers which are of ASCII types. For Floating types or others, I am getting garbage values like  -2.39030167051e+32 (for float type) 

e.g. if my system's modbus register 4 contains the value of current year and is of type UINT, then my query result  = self.client.read_holding_registers(4,1) when decoded with line 9 above. it should give me 2013 as output but I am getting a value of '7' as output which is weird.

e.g. if my system's modbus register 12 contains the value of current Time in HH:MM:SS and is of type ASCII then I would get correct output as 12:37:54

Can Anyone let me know, why is this happening?

---

Way 2: 
If instead of using read_holding_registers at line 2, I use read_input_registers and keeping rest of code as such,  then as soon as I read it it gives me error as "'ExceptionResponse' object has no attribute 'registers'"

Any help?

**Comment by alexdumitrescu** [comment]
bump!!
