### ISSUE TITLE
Opening twice a port with a sync RTU client 

### ISSUE THREAD

**Issue by dacalin** [riptideio/pymodbus#415]
### Versions

* Python: 3
* OS: mac
* Pymodbus: 2.2
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: rtu - sync
* Client: rtu- sync

### Description
Hello, 

I have a service running as a master device (sync, rtu, rs485). Now, I want to create another service in the same machine and in the same port. I know I need to implement a communication mecanism between the two services in order to ensure that only one talk at the same time.

But...Is it posible or could i get errors because I am opening the port twice in different services... I make a few test and it seems like it works.

**Comment by dhoomakethu** [comment]
You can technically use the same port but as you have correctly mentioned you need to make sure only one is talking on the bus at any given point of time.
