### ISSUE TITLE
cant installing module pymodbus[twisted]

### ISSUE THREAD

**Issue by muratguenduez** [riptideio/pymodbus#419]
from pymodbus.client.sync import ModbusTcpClient
ModuleNotFoundError: No module named 'pymodbus.client'; 'pymodbus' is not a package

i used pip procedure to install pymosbus step by step, i insatalled again visal studio build tools and sdk and the v14.0,  tried both pip and  pip3, paths were added.
but i have an error during the "pymodbus[twisted]" installing as below,

 LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158
    ----------------------------------------
ERROR: Command "'c:\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Murat\\AppData\\Local\\Temp\\pip-install-wbp52pli\\twisted\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Murat\AppData\Local\Temp\pip-record-n1cgmjtn\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Murat\AppData\Local\Temp\pip-install-wbp52pli\twisted\

**Comment by OldTinfoil** [comment]
If I were you, I would download the wheel file from Unofficial Windows Binaries for Python Extension Packages from the amazing Christoph Gohlke's site (https://www.lfd.uci.edu/~gohlke/pythonlibs/#twisted). Once downloaded, install it via `pip install c:\path\to\file`.
