### ISSUE TITLE
Example code fails - Async Asyncio Serial Client Example

### ISSUE THREAD

**Issue by itofficeeu** [riptideio/pymodbus#422]
The code from this example:
[https://github.com/riptideio/pymodbus/blob/master/examples/common/async_asyncio_serial_client.py](https://github.com/riptideio/pymodbus/blob/master/examples/common/async_asyncio_serial_client.py)

Returns:

```
$ python pymodbus_asyncio_client_example_2019.07.03-1211.py
  File "pymodbus_asyncio_client_example_2019.07.03-1211.py", line 43
    async def start_async_test(client):
            ^
SyntaxError: invalid syntax
```

After removing "async" in front of "def" - comes this error:

```
$ python pymodbus_asyncio_client_example_2019.07.03-1211.py
  File "pymodbus_asyncio_client_example_2019.07.03-1211.py", line 66
    rq = await client.write_coil(0, True, unit=UNIT)
                    ^
SyntaxError: invalid syntax

$ python --version
Python 2.7.13
```

Maybe something that should be corrected somehow ? - If it is an error?...

**Comment by dhoomakethu** [comment]
Asyncio works only on Python 3.5 and above.
