### ISSUE TITLE
SyntaxError: assignment to keyword => True, False = (1 == 1), (0 == 1)

### ISSUE THREAD

**Issue by ghost** [riptideio/pymodbus#43]
C:\Anaconda>pip install -U pymodbus
Downloading/unpacking pymodbus
  Downloading pymodbus-1.2.0.tar.gz (75Kb): 75Kb downloaded
  Running setup.py egg_info for package pymodbus
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "C:\Anaconda\build\pymodbus\setup.py", line 26, in <module>
        from pymodbus import **version**, **author**
      File "pymodbus__init__.py", line 37
        True, False = (1 == 1), (0 == 1)
           ^
    SyntaxError: assignment to keyword
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "C:\Anaconda\build\pymodbus\setup.py", line 26, in <module>

```
from pymodbus import __version__, __author__
```

  File "pymodbus__init__.py", line 37

```
True, False = (1 == 1), (0 == 1)

   ^
```

SyntaxError: assignment to keyword

---

Command python setup.py egg_info failed with error code 1 in C:\Anaconda\build\p
ymodbus
Storing complete log in \xxxx\AppData\Roaming\pip\pip.log

> > > print sys.version
> > > 2.7.5 |Anaconda 1.8.0 (32-bit)| (default, Jul  1 2013, 12:41:55) [MSC v.1500 32 bit (Intel)]

If I comment out those four lines, it works fine.

**Comment by tomkuijsten** [comment]
Just wanted to add that you could also download the source from the 3 branch and use the "python setup.py install", which will work.

**Comment by IntrepidBrit** [comment]
Downloaded from the python3 branch, used "python setup.py install" and still received the above error.

**Comment by leocor** [comment]
Same error to date.

**Comment by apalkoff** [comment]
same. python 3.5

**Comment by geoffe** [comment]
How is this issue closed?   Broken in pymodbus-1.2.0 -- is there a work-hack-around?  Is there a pymodbus-1.2.1?

**Comment by alonek1** [comment]
same problem

**Comment by alonek1** [comment]
pip install pymodbus3 will work
