### ISSUE TITLE
Access Siemens PAC3100 (RTU) via PAC4200 (TCP) 

### ISSUE THREAD

**Issue by Oliver-Prislan** [riptideio/pymodbus#442]
can somebody assist providing a __short example__ on how to read the serial meters behind a modbusTCP __gateway__ with pymodbus?

I know the PAC4200 should listen on port 17002 (mod1) for slaves and the address should be 10.

modbusTCP to port 502 to the master works quite well already.

Thank you

**Comment by dhoomakethu** [comment]
Refer https://github.com/riptideio/pymodbus/blob/master/examples/contrib/serial_forwarder.py . That could help.
