### ISSUE TITLE
Modbus daisychain

### ISSUE THREAD

**Issue by dexterhussain** [riptideio/pymodbus#445]
We have 20 Trio and 30 Trio installed , we are making a daisy chain , in daisy chain when a connection is made , first 7 are working correct , and 5 in same building are also when we connection two buildings , we start getting checksum error. Any Idea or help why is being caused?

**Comment by dhoomakethu** [comment]
Are you reading the bus at the same time ?

**Comment by dexterhussain** [comment]
reading bus means?
