### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by shnabin** [riptideio/pymodbus#448]
Hi @dhoomakethu 

Sorry for the late reply, Thank you for your support with the path issue, i am importing the def from the modbus_mapper and facing the following issue in the following function 

template = ['addr', 'fun', 'type', 'stat']
def mapping_decoder(mapping_blocks, decoder=None):

    for block in mapping_blocks.values():
        for mapping in block.values():
            print(mapping)
            print(block.values())
            mapping['addr'] = int(mapping['addr'])

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python37-32\lap.py", line 311, in mapping_decoder mapping['addr'] = int(mapping['addr'])
TypeError: string indices must be integers

when printing the print(mapping) & print(block.values()) i am receiving the following output :
40001
dict_values(['40001', 'int', 'Pac'])

Please suggest how to solve this issue. Also, can you please update the modbus_mapper file which is compatible with the latest pymodbus version.

_Originally posted by @krishnacy in https://github.com/riptideio/pymodbus/issues/433#issuecomment-534929361_

**Comment by krishnacy** [comment]
Hi @dhoomakethu 

Any idea till when modbus_mapper example new release comes out ?

**Comment by dhoomakethu** [comment]
@krishnacy honestly I have no timeline in mind. I am hopeful to clear the backlog next month. Hopefully end of may ,there should be a new release

**Comment by krishnacy** [comment]
Hi @dhoomakethu , any chance of new release this month!
