### ISSUE TITLE
Read the docs v2.2.0 link is dead

### ISSUE THREAD

**Issue by fkromer** [riptideio/pymodbus#449]
### Versions

* Pymodbus: v2.2.0

### Description

I'd like to reference the specific pymodbus documentation v2.2.0 on read the docs in a project. It seems like version specific documentation is generated, but the link to the docs of the version in question is dead: [pymodbus.readthedocs.io (v.2.2.0)](https://pymodbus.readthedocs.io/en/v2.2.0/) Will this link work as soon as v2.2.0 is no the latest version anymore?

**Comment by dhoomakethu** [comment]
Latest should be pointing to be referencing to v2.2.0 . I will check why the link is broken

**Comment by dhoomakethu** [comment]
https://pymodbus.readthedocs.io/en/v2.3.0/
