### ISSUE TITLE
Please add a float16 formatter for the REPL

### ISSUE THREAD

**Issue by andrey-gvrd** [riptideio/pymodbus#455]

**Comment by dhoomakethu** [comment]
modbus at the end of the day can only deal with integers, to convert float in to integer (ieee754 single precision float format) pymodbus depends on Python built in library `struct` , which requires a minimum 4 bytes(32 bits) as input and hence we only support float32 and float64

**Comment by tracernz** [comment]
[Is it not `e`](https://docs.python.org/3.8/library/struct.html#format-characters)? Look like [it was added in Python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html#struct) and not supported in 2.7.

**Comment by dhoomakethu** [comment]
@tracernz thanks for the hint. I will have it added to the pymodbus to-do list.

**Comment by dhoomakethu** [comment]
Fixed with v2.3.0
