### ISSUE TITLE
ERROR: pymodbus 2.2.0 has requirement six==1.11.0, but you'll have six 1.12.0 which is incompatible.

### ISSUE THREAD

**Issue by iudeen** [riptideio/pymodbus#456]
ERROR: pymodbus 2.2.0 has requirement six==1.11.0, but you'll have six 1.12.0 which is incompatible. On installing pymodbus alongside Azure Iot edge for using in a dockerized iot edge deployment. 

Upgrading the library to use latest six requested.

**Comment by dhoomakethu** [comment]
This is fixed in `pymodbus==2.3.0rc1`
