### ISSUE TITLE
MyPy type annotations

### ISSUE THREAD

**Issue by lovasoa** [riptideio/pymodbus#476]
### Description

Type annotations allow programmers to automatically check whether code uses APIs with the right parameter types. They are very useful and often prevent bugs. It would be great if this project could provide [mypy type annotations](https://mypy.readthedocs.io/en/latest/stubs.html).

**Comment by dhoomakethu** [comment]
@lovasoa thanks for the suggestion. Right now I do not have enough bandwidth for this. I will be more than happy to accept a PR.

**Comment by lovasoa** [comment]
Great ! Can we keep the issue open until then ? It will give it more visibility. Maybe you could add a "help wanted" label ?
