### ISSUE TITLE
Win7 ImportError: No module named pymodbus.client.sync

### ISSUE THREAD

**Issue by irbigturtle** [riptideio/pymodbus#49]
It appears to have successfully installed, and the .egg file is in site-packages, but I can't import. 

If I run setup.py --version it returns 1.2.0, but when I try to import... 

from pymodbus.client.sync import ModbusTcpClient

Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    from pymodbus.client.sync import ModbusTcpClient
ImportError: No module named pymodbus.client.sync

INSTALL LOG

> setup.py install
> running install
> running bdist_egg
> running egg_info
> writing requirements to pymodbus.egg-info\requires.txt
> writing pymodbus.egg-info\PKG-INFO
> writing top-level names to pymodbus.egg-info\top_level.txt
> writing dependency_links to pymodbus.egg-info\dependency_links.txt
> warning: manifest_maker: standard file 'setup.py' not found

file ez_setup.py (for module ez_setup) not found
reading manifest file 'pymodbus.egg-info\SOURCES.txt'
writing manifest file 'pymodbus.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
file ez_setup.py (for module ez_setup) not found
file ez_setup.py (for module ez_setup) not found
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

creating build\bdist.win32\egg
creating build\bdist.win32\egg\EGG-INFO
copying pymodbus.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying pymodbus.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying pymodbus.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO

copying pymodbus.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying pymodbus.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
copying pymodbus.egg-info\zip-safe -> build\bdist.win32\egg\EGG-INFO
creating 'dist\pymodbus-1.2.0-py2.7.egg' and adding 'build\bdist.win32\egg' to i
t
removing 'build\bdist.win32\egg' (and everything under it)
Processing pymodbus-1.2.0-py2.7.egg
Removing c:\python27\lib\site-packages\pymodbus-1.2.0-py2.7.egg
Copying pymodbus-1.2.0-py2.7.egg to c:\python27\lib\site-packages
pymodbus 1.2.0 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\pymodbus-1.2.0-py2.7.egg
Processing dependencies for pymodbus==1.2.0
Searching for pyserial==2.7
Best match: pyserial 2.7
Adding pyserial 2.7 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for twisted==14.0.0
Best match: twisted 14.0.0
Processing twisted-14.0.0-py2.7-win32.egg
twisted 14.0.0 is already the active version in easy-install.pth
Installing cftp.py script to C:\Python27\Scripts
Installing cftp.pyc script to C:\Python27\Scripts
Installing ckeygen.py script to C:\Python27\Scripts
Installing ckeygen.pyc script to C:\Python27\Scripts
Installing conch.py script to C:\Python27\Scripts
Installing conch.pyc script to C:\Python27\Scripts
Installing lore.py script to C:\Python27\Scripts
Installing lore.pyc script to C:\Python27\Scripts
Installing mailmail.py script to C:\Python27\Scripts
Installing mailmail.pyc script to C:\Python27\Scripts
Installing manhole.py script to C:\Python27\Scripts
Installing manhole.pyc script to C:\Python27\Scripts
Installing pyhtmlizer.py script to C:\Python27\Scripts
Installing pyhtmlizer.pyc script to C:\Python27\Scripts
Installing tap2deb.py script to C:\Python27\Scripts
Installing tap2deb.pyc script to C:\Python27\Scripts
Installing tap2rpm.py script to C:\Python27\Scripts
Installing tap2rpm.pyc script to C:\Python27\Scripts
Installing tapconvert.py script to C:\Python27\Scripts
Installing tapconvert.pyc script to C:\Python27\Scripts
Installing tkconch.py script to C:\Python27\Scripts
Installing tkconch.pyc script to C:\Python27\Scripts
Installing trial.py script to C:\Python27\Scripts
Installing trial.pyc script to C:\Python27\Scripts
Installing twistd.py script to C:\Python27\Scripts
Installing twistd.pyc script to C:\Python27\Scripts

Using c:\python27\lib\site-packages\twisted-14.0.0-py2.7-win32.egg
Searching for zope.interface==4.1.1
Best match: zope.interface 4.1.1
Processing zope.interface-4.1.1-py2.7-win32.egg
zope.interface 4.1.1 is already the active version in easy-install.pth

Using c:\python27\lib\site-packages\zope.interface-4.1.1-py2.7-win32.egg
Searching for setuptools==5.2
Best match: setuptools 5.2
Processing setuptools-5.2-py2.7.egg
setuptools 5.2 is already the active version in easy-install.pth
Installing easy_install-script.py script to C:\Python27\Scripts
Installing easy_install.exe script to C:\Python27\Scripts
Installing easy_install.exe.manifest script to C:\Python27\Scripts
Installing easy_install-2.7-script.py script to C:\Python27\Scripts
Installing easy_install-2.7.exe script to C:\Python27\Scripts
Installing easy_install-2.7.exe.manifest script to C:\Python27\Scripts

Using c:\python27\lib\site-packages\setuptools-5.2-py2.7.egg
Finished processing dependencies for pymodbus==1.2.0

**Comment by ujwalashirodkar21** [comment]
I am facing the same problem of importing inspite of successful installation of pymodbus

ModuleNotFoundError: No module named 'pymodbus'

**Comment by monkphx** [comment]
This worked for me
sudo pip install pymodbus --upgrade

**Comment by Benblob688** [comment]
Note for me the issue was that an older version of `pymodbus` used the syntax:
`from Pymodbus.client.sync import ModbusTcpClient` 
whereas now the Docs suggest that the `sync` has been dropped and the correct syntax is:
`from Pymodbus.client import ModbusTcpClient`

**Comment by bumlard** [comment]
Benblob688 nailed it, get rid of .sync

**Comment by RabenFlug** [comment]
After removing the .sync, I get this:
`DEBUG:growattRS232:GrowattRS232 initialized with usb port /dev/ttyUSB0 and modbus address 1.
Error: TypeError("__init__() got multiple values for argument 'unit'")`
Does anybody know what can cause this?

**Comment by janiversen** [comment]
you are calling with unit=, change that to slave=

**Comment by janiversen** [comment]
It is a good thing to read the documentation, upgrading to version 3, calls for some modification of your source.
