### ISSUE TITLE
Maximum value for count at read_holding register

### ISSUE THREAD

**Issue by rodrigorpgsc** [riptideio/pymodbus#490]
### Versions

* Python: 3.6.9-64bits
* OS:Ubuntu bionic64
* Pymodbus: 2.2.0
* Modbus Hardware (if used):  None

### Pymodbus Specific
* Client: tcp - sync

### Description

The ammount of register from read_holding_register don`t sound rigth if the size is above 128. If you run the code below you`ll able to see the behaviour

### Code and Logs

```
con = ModbusTcpClient('10.0.2.2', '502')
result = con.read_holding_registers(1, 127)
len(result.registers)
result2 = con.read_holding_registers(1, 129)
len(result2.registers)

```
The output is 127 and 1, but should be 127 and 129. What is wrong at my code?

**Comment by dhoomakethu** [comment]
The max number of registers you can poll using read_holding_registers is 125 as per modbus specs, And it is not guaranteed if any number greater than that would yield a proper value. you will have to split up your reads .

**Comment by rodrigorpgsc** [comment]
ah ok, I didn`t know that! Thanks for your reply
