### ISSUE TITLE
'ModbusTcpClient' object has no attribute 'handle_local_echo' if client != ModbusSerialClient

### ISSUE THREAD

**Issue by wildstray** [riptideio/pymodbus#494]
Branch: dev

  File "/home/andrea/LWE/MPO/Myna/wolf/pymodbus/transaction.py", line 242, in _transact
    if self.client.handle_local_echo is True:
AttributeError: 'ModbusTcpClient' object has no attribute 'handle_local_echo'

Suggested fix:

```if getattr(self.client, 'handle_local_echo', False) is True:```

Instead of:

```if self.client.handle_local_echo is True:```

**Comment by gcbirzan** [comment]
```python
if getattr(self.client, 'handle_local_echo'):
```
Is the pythonic way of doing that.

**Comment by dhoomakethu** [comment]
Fixed with https://github.com/riptideio/pymodbus/commit/e402d9fdd2f1f8a4e178b8da0c28b3b17aeefac3#diff-40a48d0b5cf576d37ccece3543183f65R242
Please give a try with this branch https://github.com/riptideio/pymodbus/tree/asyncio-bug-fixes
