### ISSUE TITLE
pymodbus.client.sync import ModbusTcpClient -error #244

### ISSUE THREAD

**Issue by akashb12** [riptideio/pymodbus#498]
### Versions

* Python:
* OS:
* Pymodbus:
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
 # code and logs here.

```

**Comment by dhoomakethu** [comment]
Closing as no description is available
