### ISSUE TITLE
Firsrst message is rejected

### ISSUE THREAD

**Issue by smoczy25** [riptideio/pymodbus#510]
https://github.com/riptideio/pymodbus/blob/master/pymodbus/framer/rtu_framer.py
Bad init of self._header, first message validation rise error of unit mismatch

### Versions

* Python:
* OS:
* Pymodbus:
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
 # code and logs here.

```

**Comment by janiversen** [comment]
Solved on dev.
