### ISSUE TITLE
Pymodbus DE/RE RS485 pin control

### ISSUE THREAD

**Issue by BullT** [riptideio/pymodbus#519]
Hi,

How can I control the DE/RE pin in my RS485 board if I using the Pymodbus library?

Can I configure the Pymodbus for use the DE/RE pin automaticly?

Thanks, XCO

**Comment by dhoomakethu** [comment]
Pymodbus uses pyserial to communicate over serial bus and accepts all the parameters pyserial takes . Refer https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial .

**Comment by Simonefardella** [comment]
@dhoomakethu i have a MAX485 module wired like this one: 
![image](https://user-images.githubusercontent.com/5062855/93869285-e17f5300-fccb-11ea-8338-d5ec6934a1b7.png)

Actually i'm not able to figure out how to control the RE/DE pin from the library using the [Synchronous Client Example](https://pymodbus.readthedocs.io/en/latest/source/example/synchronous_client.html)

How i can control the RE/DE pin using a common (in my case the 23) GPIO? 
Thanks!
