### ISSUE TITLE
Examples related to Modbus TLS connection.

### ISSUE THREAD

**Issue by LordGameleo** [riptideio/pymodbus#530]
### Versions

* Python: Python3
* OS: Ubuntu
* Pymodbus: Latest
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tls - sync/async
* Client: tls - sync/async

### Description

Is there any example related to ModbusTLS Connection? Both Server and Client Side. 
How can I test both? Is there any software for it?

**Comment by LordGameleo** [comment]
Never Mind. I found it in comments of PR https://github.com/riptideio/pymodbus/pull/439 .  If possible please add direct link to the Readme.md

**Comment by dhoomakethu** [comment]
Just in case. Here are the examples.

https://github.com/riptideio/pymodbus/blob/dev/examples/common/synchronous_server.py#L122

**Comment by LordGameleo** [comment]
@dhoomakethu thanks for response over such a short time. Found it. But why do we have client example in /contrib/ and server example in /common/ Can we create a simple example for server as well in /contrib/ directory?

**Comment by dhoomakethu** [comment]
@LordGameleo those examples are provided by the contributors and hence are maintained there.
