### ISSUE TITLE
Connect to Multiple Clients & Act as Gateway

### ISSUE THREAD

**Issue by shnabin** [riptideio/pymodbus#539]
Hi,

### Versions

* Python: 3.7.4
* OS: Windows
* Pymodbus:
* Modbus Hardware (if used): ABB, GE, Siemens  

### Pymodbus Specific
* Server: tcp
* Client: tcp

### Description

Hi,

I need help with the following 2 points.

1. Is it possible to connect to multiple hosts/clients in one instance, 
(Ex: Server IP : 192.168.1.1 , Client IP : 192.168.1.2, 192.168.1.3, etc) port 502, If its possible kindly provide an example.

2. From point 1, once I read the data from multiple clients, can the modbus server act as a gateway and give the data further to other devices. Ex: 192.168.1.2 (host/client) --> (server) 192.168.1.1 (client/host) --> 192.168.10.2. If its possible kindly provide an example.

Appreciate your help. Thank you !!

**Comment by dhoomakethu** [comment]
Yes, you can connect to multiple servers but you will have to use multiple clients as well. you can also take a look at https://github.com/riptideio/pymodbus/blob/master/examples/contrib/concurrent_client.py  and https://github.com/riptideio/pymodbus/blob/master/examples/contrib/remote_server_context.py
