### ISSUE TITLE
Question: Create ModBus Proxy  using pymodbus

### ISSUE THREAD

**Issue by JeremyRitchie** [riptideio/pymodbus#543]
### Description

Hi,

I'm trying to create a modbus server which will act as a proxy for modbus. 
It will receive modbus commands and then execute those commands on a downstream modbus server, and then return the result to the original requester.

How can i implement this with pymodbus? 

I've been searching online and unable to find something suitable. 

Thanks

**Comment by dhoomakethu** [comment]
You can take a look in to the below examples
https://github.com/riptideio/pymodbus/blob/master/examples/contrib/serial_forwarder.py
https://github.com/riptideio/pymodbus/blob/master/examples/contrib/remote_server_context.py
https://github.com/riptideio/pymodbus/blob/master/examples/common/callback_server.py
