### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by swamper123** [riptideio/pymodbus#544]
### Versions
* Python: >=3.6
* Pymodbus: >= 2.4

### Description

I haven't found in the Readme, which Python versions shall be supported  here ("it should work fine under any python version > 2.7 (including python 3+)").

Python 2 is dead since this year (and may have been dead a long time ago, I mean the lifecycle was more than 9 years), so there won't be more fixes, it will just cause more problems to be compatible with future Python versions.
There been have many things happening in the Python 3 world as well, esepcially in the async section with Python3.6.

Being compatible across these worlds makes the code more complex, slower and unsafer, especially if the Python3 developement goes on.

I would recommened to drop support for all Python versions <3.6 (or even start with 3.7 and go up to 3.9) and explicit mention that in the README.

EDIT: This log from Travis will also may cause problems in the near future as well: 

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

EDIT: If that PR may clear where we are going with versions, I guess #513 and #534  can be tackled as well

<sup><sup>Funfact: Python3 support was added ~7years ago for this library </sup></sup>

**Comment by dhoomakethu** [comment]
Python2 support will be removed from pymodbus 3.x onwards. JFYI.

**Comment by swamper123** [comment]
Thanks for the information.
I will start some cleanup PRs already ;)

**Comment by swamper123** [comment]
With the new default branch 3.0.0 and #564 merged, this issue is solved.
Case closed. :detective:
