### ISSUE TITLE
How to read the message which is being sent to modbus device in order to receive data from it ?

### ISSUE THREAD

**Issue by Abbad-Zafar** [riptideio/pymodbus#553]
### Versions

* Python:
* OS:
* Pymodbus:
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
 # code and logs here.

```

**Comment by Abbad-Zafar** [comment]
@dhoomakethu

**Comment by dhoomakethu** [comment]
Can you be more specific please?, I am not quite getting the question.

**Comment by Abbad-Zafar** [comment]
I want the hex response or packet which the master sends to slave or vice versa

**Comment by l337quez** [comment]
I would like to know how to read the complete message including reading the unit id

**Comment by dhoomakethu** [comment]
@Abbad-Zafar there is no direct way at present to get raw response. You may have to reverse engineer the registers to get the frame.

**Comment by Abbad-Zafar** [comment]
@dhoomakethu Doesn't the logging show info about packets ? What are being sent and what are being received ?

**Comment by dhoomakethu** [comment]
You can view the data if you running with level debug.

**Comment by nhi-vanye** [comment]
A spin out RFE for Serial would be to use `serial.serial_for_url()` instead of `serial.Serial()` to allow the `spy://` url schema to be used.

https://pyserial.readthedocs.io/en/latest/url_handlers.html
