### ISSUE TITLE
TCP Client and Server identification

### ISSUE THREAD

**Issue by JonAlberdi** [riptideio/pymodbus#571]
### Versions

* Python: 3.8
* OS: Ubuntu
* Pymodbus: 2.4

### Pymodbus Specific
* Server: tcp - sync/async
* Client: tcp - sync/async

### Description

Hi,

I have a couple of questions in regard to the TCP connection between a Client and a Server. I am using the common examples, both sync and async.

-In the server example an Identification is defined for the server, is this identification sent to the client? And if it is, how can I access it?

-Would there be any possibility to grant the client a similar type of identification and send it to the server?

Thank you for your attention.

**Comment by dhoomakethu** [comment]
You can run `ReadDeviceIdentification` to fetch those values from the server. refer https://github.com/riptideio/pymodbus/blob/master/examples/common/synchronous_client_ext.py#L81
The modbus spec does not specify any such identification for client, hence its not supported on the client.
