### ISSUE TITLE
Repl client single write register issue (resp.count)

### ISSUE THREAD

**Issue by ot2789** [riptideio/pymodbus#573]
Hello! I have a problem with the pymodbus library when writing a single register value. 
This is the error that I get:

**client.write_register(int(address), int(value), unit=self.__unit)**
  File "/usr/local/lib/python3.6/dist-packages/pymodbus/repl/client.py", line 50, in _wrapper
    'count': resp.count

Problem is in this file: https://github.com/riptideio/pymodbus/blob/master/pymodbus/register_write_message.py
The singular write register classes do not define the .count field inside them.

**Comment by dhoomakethu** [comment]
@ot2789 what version of pymodbus are you using ? Can you share the command the you are using which resulted in this error?

**Comment by dhoomakethu** [comment]
@ot2789 please give a try with `2.5.0` and let me know if that fixes issue.

**Comment by ot2789** [comment]
> @ot2789 what version of pymodbus are you using ? Can you share the command the you are using which resulted in this error?

I am using 2.4.0. So the last released version. I will update to 2.5.0 to see if it is fixed.

**Comment by ot2789** [comment]
> @ot2789 please give a try with `2.5.0` and let me know if that fixes issue.

Is there a way to install this via PIP? Or do I need to do the manual installation?

**Comment by dhoomakethu** [comment]
@ot2789 sorry for the delay, try with `pip install git+https://github.com/riptideio/pymodbus.git@2.5.0`

**Comment by dhoomakethu** [comment]
Fixed with 2.5.0rc1. Please install from https://pypi.org/project/pymodbus/2.5.0rc2/ .
Refer https://github.com/riptideio/pymodbus/releases

**Comment by ot2789** [comment]
Hello! Yes the newest version fixed the problem! Thanks alot!
