### ISSUE TITLE
Extract client IP from server

### ISSUE THREAD

**Issue by JonAlberdi** [riptideio/pymodbus#586]
### Versions

* Python: 3
* OS: Ubuntu
* Pymodbus: 2.4

### Pymodbus Specific
* Server: tcp - sync
* Client: tcp - sync

### Description

Hi,

I am working on a project that uses the TCP sync server and TCP sync client examples and I ran into a problem that I am not sure how to solve. When using the "StartTCPserver" or "ModbusTCPserver" functions, I would like to extract the IP of the client that connects to it, compare this IP with another IP that I have stored previously and if it is the same, continue running the server. How can I stop the server and extract the IP of the client?

Thank you in advance.

**Comment by dhoomakethu** [comment]
There is no direct way of fetching this information,  You will have to write your `handler` derived from `ModbusConnectedRequestHandler` and override `setup` method to update an attribute in the server.

Something like this

```
class MyModbusTcpServer(ModbusTcpServer):
    def __init__(self, *args, **kwargs):
         super(MyModbusTcpServer, self).__init__(**args, *kwargs)
         self.connected_clients = []

class MyRequestHandler(ModbusConnectedRequestHandler):
   def setup(self):
        """ Callback for when a client connects
        """
        super(MyRequestHandler, self).setup()
        self.server.connected_clients.append(self.client_address)

server = MyModbusTcpServer(<args>, handler=MyRequestHandler)
server.serve_forever()
```
Refer https://github.com/riptideio/pymodbus/blob/master/pymodbus/server/sync.py#L46

Note, `serve_forever()` is blocking.
