### ISSUE TITLE
Include tests in coverage checks

### ISSUE THREAD

**Issue by altendky** [riptideio/pymodbus#598]
It is valuable to include tests in coverage checks to make sure that all your tests are actually running and to catch any dead code in them.  I can add this but figured I wouldn't mix it in to the present pile of CI PRs.

**Comment by altendky** [comment]
Despite not having been commented on, this is in fact still valuable.

**Comment by altendky** [comment]
Still running around on other tasks and haven't made it back here yet.

**Comment by altendky** [comment]
oh yeah, i should look at this.  at some point.  (activity!)

**Comment by janiversen** [comment]
As far as I can see, tests are included in all CI checks

**Comment by janiversen** [comment]
I misunderstood you. Your PR is good.

**Comment by janiversen** [comment]
PR merged.
