### ISSUE TITLE
ModbusSerialClient socket closed after first read

### ISSUE THREAD

**Issue by thunderbug1** [riptideio/pymodbus#616]
I recently upgraded from python 2.7 to python 3.8.5
The code uses the Pymodbus library to connect to a ups and to periodically read some values.

In python2 the is_socket_open method returned true as long as the device was connected, but with python3 is_socket_open returns false after the first read (even though further reads work )

`
#The connection is established like:

BAUDRATE=115200
STOP_BITS=1
START_BITS=1
BYTESIZE=8
PARITY="E"
SLAVE_ID = 192
ups_port= "/dev/ttyUSB0"

client = ModbusSerialClient(method='rtu', port=ups_port, timeout=1, baudrate=BAUDRATE, stopbits=STOP_BITS, startbits=START_BITS, bytesize=BYTESIZE, parity=PARITY, )

client.connect() # this returns true

#Then I check the connection like:

connected = self.client.is_socket_open()
print(f"connect connected = {connected}")  # this prints "true"

rr = client.read_input_registers(0x4202,1, unit=SLAVE_ID) # the register is correctly read
if rr.isError():
            rospy.logerr("encountered pymodbus exception_code: {}".format(ModbusExceptions.decode(rr.exception_code)))  # no exceptions are encountered

connected = client.is_socket_open()
print(f"connect connected = {connected}")  # this prints "false"
`

**Comment by dhoomakethu** [comment]
Please try `pymodbus==2.5.1rc1` or you can add a small sleep between your reads.

**Comment by aetasoul** [comment]
https://github.com/riptideio/pymodbus/issues/612

https://stackoverflow.com/questions/66526532/after-read-holding-registers-with-pymodbus-connection-is-broken-in-raspberry-pi/66581700?noredirect=1#comment117707861_66581700

**Comment by thunderbug1** [comment]
ok thank you very much for your answers, the fix with pymodbus==2.5.1rc1 resolved the issue for me :)
