### ISSUE TITLE
pymodbus.server.sync: chuid server on bind

### ISSUE THREAD

**Issue by sjlongland** [riptideio/pymodbus#63]
Hi,

I've looked around and while I can get the PyModbus server to bind to port 502 as root, this represents a possible security risk and gives us other headaches (like files being created as root).  Obviously port 502 can't be bound to by an unprivileged process and a lot of software (e.g. MacroView SCADA) assumes it'll find Modbus on that port, so we're more or less stuck there.

Many daemons will start as root, bind to a port, then drop privileges.  Apache httpd is a good example of this.  How is this achieved with PyModbus?

**Comment by bashwork** [comment]
I didn't add a whole lot of infrastructure for creating advanced daemons, however if you are using the twisted stack, you can use tac files and achieve everything you want:

http://www.tsheffler.com/blog/?p=526

I can add a feature request for this, however it may be a minute before I can get to it.

**Comment by memetb** [comment]
You should investigate `authbind`. Changing anything inside this library to essentially emulate what authbind gives you is probably not good security practice.
