### ISSUE TITLE
How to get response code in case of an exception / Provide a way to access raw data received with exception response

### ISSUE THREAD

**Issue by protocolpy** [riptideio/pymodbus#636]
### Versions

* Python:
* OS:
* Pymodbus:
* Modbus Hardware (if used): 

### Pymodbus Specific

* Client: tcp/rtu/- sync

### Description

Hello! 
I would like to get the exception code returned from a server when polling for a holding register. I know it shows when debug logging is enabled, but would like to record it for test purposes. Is this possible with the api on both tcp as well as serial. 
IsError() prints the exception string, but not the full response with the exception code. 

Thank you in advance!!

### Code and Logs

```python
 # code and logs here.

```

**Comment by protocolpy** [comment]
Sorry I didn't elaborate. The exception is of type ModbusIOexception 
Modbus Error: [Input/Output] No Response received from the remote unit/Unable to decode response
When I print(message.ExceptionResponse.exception_code), the ModbusIOexception class doesn't have ExceptionResponse

**Comment by dhoomakethu** [comment]
`ModbusIOException` are raised when pymodbus coudn't find a response on time (empty response) or the CRC validation fails. In either case there wont be a standard modbus exception code that could be derived. However the original function code of the request could be tracked with attribute `fcode` https://github.com/riptideio/pymodbus/blob/master/pymodbus/exceptions.py#L33

**Comment by protocolpy** [comment]
DEBUG:pymodbus.transaction:RECV: 0x0 0x2 0x0 0x0 0x0 0x5 0x1 0x86 0x1

This is the response I get. If it times out and not recognizing the response error code, how can I retrieve the response itself so I could record the code, instead of logging?

**Comment by dhoomakethu** [comment]
Unfortunately, pymodbus discards the message. I will take this as an enhancement so that the raw data is available with exception response.

**Comment by protocolpy** [comment]
Hello
Can you please clarify on these questions below..
1. Retries don't seem to work in TCP but works well for RTU. I have added manual retries on error response to TCP in my code.
2. Is there a way I can reduce the debug level to print only the send and receive responses
