### ISSUE TITLE
Modbus updating server sending fin/ack to query

### ISSUE THREAD

**Issue by OldTinfoil** [riptideio/pymodbus#638]
### Versions

* Python: 3.5.3
* OS: Raspbian GNU/Linux 9 (stretch)
* Pymodbus: 2.3.0 (suspected - still looking to confirm)
* Modbus Hardware (if used): n/a

### Pymodbus Specific
* Server: tcp - (updating) sync
* Client: 3rd party software

### Description

System is being polled every 30s, but with multiple queries per "round". After the 5th successful query, the 6th query is ACK'd and bundled with an solicited FIN. Cannot currently reproduce on local test systems. In the process of requesting more information as the system is remote and not easily accessible. I have attached a network capture (pcap) file to this issue.

I will be seeking access to the system in question so I can access the log files. If I cannot locate the problem, I will seek to update the remote system to the newest version of pymodbus to see if it alleviates the problem.

In the meantime, I will keep attempting to reproduce the problem locally. If I can create a reproducible state/code I will share here. Any suggestions on what to look for on the remote system would be greatly appreciated.

### Code and Logs
```python
# As soon as I can reproduce the problem, will create a minimal, complete, verifiable example
# Logs - work in progress.
```
[network_capture.zip](https://github.com/riptideio/pymodbus/files/6553759/network_capture.zip)

**Comment by OldTinfoil** [comment]
Apologies - accidentally hit enter too early. Still editing the issue.

**Comment by OldTinfoil** [comment]
There we go. Finished butchering this issue.

**Comment by dhoomakethu** [comment]
@OldTinfoil Do you also observe the same with Pymodbus 2.5.2?

**Comment by OldTinfoil** [comment]
We haven't been able to replicate the issue with the version in use in the lab, nor with 2.5.2. Due to the pandemic, I haven't been able to travel to the remote site to investigate the issue in person. I'll loop back around if I make any headway with the issue.
