### ISSUE TITLE
ImportError: No module named custom_message

### ISSUE THREAD

**Issue by xavidotcat** [riptideio/pymodbus#663]
I have the next issue... 

debian@beaglebone:/usr/bin/modbus$ sudo python modbus_server.py
Traceback (most recent call last):
  File "modbus_server.py", line 24, in <module>
    from custom_message import CustomModbusRequest
ImportError: No module named custom_message

Any can help me? Thanks

**Comment by dhoomakethu** [comment]
You need to make sure your `PYTHONPATH` is correct. Your import statement says you need to have `custom_message.py` file in the same directory as the `modbus_server.py`.
