### ISSUE TITLE
ignore_missing_slaves parameter has no effect

### ISSUE THREAD

**Issue by FabianInostroza** [riptideio/pymodbus#666]
### Versions

* Python: 3.9.7
* OS: Debian Testing
* Pymodbus: git master
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync, async not tested

### Description

The parameter `ignore_missing_slaves` of the servers is ignored, the servers always ignores requests to missing slaves and doesn't generate any responses.

### Code and Logs

```python
 # code and logs here.

```

**Comment by janiversen** [comment]
This is handled in sync:
```
except NoSuchSlaveException:
            txt = f"requested slave does not exist: {request.unit_id}"
            _logger.debug(txt)
            if self.server.ignore_missing_slaves:
                return  # the client will simply timeout waiting for a response
```

Closing issue.
