### ISSUE TITLE
unit parameter

### ISSUE THREAD

**Issue by ferdymercury** [riptideio/pymodbus#673]
### Versions

GitHub master

### Description

When using pymodbus within an IDE like Spyder3, some ModbusSerialClient functions contain a 'hidden' parameter, namely one that does not appear as autocompletion, and that can only be found by looking in the docstrings by opening the source code. I am referring to parameter 'unit' in https://github.com/riptideio/pymodbus/blob/master/pymodbus/repl/client/mclient.py
![image](https://user-images.githubusercontent.com/10653970/136581600-7ad8073e-4cce-40a3-b3e3-b8c07e0c2003.png)

It's only in the docstrings that one can find about how this parameter can be tuned. I needed to tune it from default's 0 to 1 and could not find how in the beginning.

![image](https://user-images.githubusercontent.com/10653970/136581383-d8e7e25f-c1d7-4f18-b02f-596671f68c38.png)

I suggest to change the function declaration as follows:

`def read_holding_registers(self, address, count=1, unit=0, **kwargs):`

There are several more functions with that hidden parameter in that file.

**Comment by iceisfun** [comment]
Should functions like read_holding_registers have a custom timeout parameter?

**Comment by dhoomakethu** [comment]
@iceisfun the read time out is applicable for all transactions, Do you have a specific use case why you would need that ?

**Comment by pkubanek** [comment]
@ferdymercury can you please check my fix really fix the issue? https://github.com/pkubanek/pymodbus. Thanks

**Comment by janiversen** [comment]
Just had a quick view of your commit, looks good, suppose you are going to submit a PR at some point in time ?

**Comment by ferdymercury** [comment]
Thanks for the fix! I tried to install and check, but my OS is a bit old and I get an error with the requirements:

```
ERROR: Could not find a version that satisfies the requirement bandit==1.7.4 (from versions: 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.13.2, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.2, 0.17.3, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2)
ERROR: No matching distribution found for bandit==1.7.4
```

But otherwise it looks quite good!

**Comment by janiversen** [comment]
bandit is only needed for development not for runtime.

**Comment by janiversen** [comment]
I mean it is only needed for Pymodbus development, not if you develop an application.

**Comment by pkubanek** [comment]
PR: https://github.com/riptideio/pymodbus/pull/1041
