### ISSUE TITLE
write_register does not accept negavive values

### ISSUE THREAD

**Issue by russalex83** [riptideio/pymodbus#676]
I am trying to write a value to a register 2700 to a VenusOS via ModbusTCP which controls Victron Multiplus Grid setpoint output. It works with all the positive values, so if I get extra energy from my solar or batteries I need to push back to the GRID in this case need to set negative value in register 2700.

`from pymodbus.client.sync import ModbusTcpClient as ModbusClient

CONNECTION = ModbusClient(host='192.168.1.125', port=502)

write_register = 2700
write_grid_setpoint_value = **-100**

CONNECTION.write_register(write_register, write_grid_setpoint_value)
print 'Setting GRID SetPoint to: ', write_grid_setpoint_value

read_register = 2700
read_qty = 1

RR = CONNECTION.read_holding_registers(read_register, read_qty)
print 'Input was: ', RR.getRegister(0)

CONNECTION.close()

### Versions

* Python: 2.7
* OS: Raspberry Pi OS
* Pymodbus:
* Modbus Hardware (if used): N/A

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
 # code and logs here.

from pymodbus.client.sync import ModbusTcpClient as ModbusClient

CONNECTION = ModbusClient(host='192.168.1.125', port=502)

write_register = 2700
write_grid_setpoint_value = -100

CONNECTION.write_register(write_register, write_grid_setpoint_value)
print 'Setting GRID SetPoint to: ', write_grid_setpoint_value

read_register = 2700
read_qty = 1

RR = CONNECTION.read_holding_registers(read_register, read_qty)
print 'Input was: ', RR.getRegister(0)

CONNECTION.close()
```

LOG:

pi@raspberrypi:~ $ python GridSetpoint2.py
Traceback (most recent call last):
  File "GridSetpoint2.py", line 9, in <module>
    CONNECTION.write_register(write_register, write_grid_setpoint_value)
  File "/home/pi/.local/lib/python2.7/site-packages/pymodbus/client/common.py", line 92, in write_register
    return self.execute(request)
  File "/home/pi/.local/lib/python2.7/site-packages/pymodbus/client/sync.py", line 109, in execute
    return self.transaction.execute(request)
  File "/home/pi/.local/lib/python2.7/site-packages/pymodbus/transaction.py", line 178, in execute
    broadcast=broadcast
  File "/home/pi/.local/lib/python2.7/site-packages/pymodbus/transaction.py", line 271, in _transact
    packet = self.client.framer.buildPacket(packet)
  File "/home/pi/.local/lib/python2.7/site-packages/pymodbus/framer/socket_framer.py", line 206, in buildPacket
    data = message.encode()
  **File "/home/pi/.local/lib/python2.7/site-packages/pymodbus/register_write_message.py", line 42, in encode
    packet += struct.pack('>H', self.value)
struct.error: integer out of range for 'H' format code**

**Comment by tracernz** [comment]
You need to pack the value into an unsigned 16-bit int yourself if using raw register read/write.

**Comment by dhoomakethu** [comment]
@russalex83 refer https://github.com/riptideio/pymodbus/blob/master/examples/common/modbus_payload.py#L100 to send signed values.
