### ISSUE TITLE
Incomplete data received from pl1000e module

### ISSUE THREAD

**Issue by signix** [riptideio/pymodbus#68]
Using ModbusTcpClient to connect to pl1000e module I received only the first part of the response and not the registers for some of them (firmware MAY05).
After investigation it semms that the tcp response is send as two sequences
.
If I add this line to transaction.py (line 68) everything is ok
result = self.client._recv(1024)
++ if len([hex(ord(x)) for x in result]) <= 7:
++     result += self.client._recv(1024)
Do you have any idea to solve this problem with a better solution ?
Thank you and sorry for my english

**Comment by dhoomakethu** [comment]
Already addressed with #251
