### ISSUE TITLE
the asynctest library used in test suite is abandoned, not supported with Python 3.9+

### ISSUE THREAD

**Issue by Apteryks** [riptideio/pymodbus#681]
All is in the title; see: https://github.com/Martiusweb/asynctest/issues/158.

**Comment by swamper123** [comment]
I would recommened to replace asynctest with `pytest-asyncio` which is a plugin for pytest.

In later future versions we may be able to switch to the inbuilt solution from python, since unittests supports async stuff in ... 3.9 I guess? But that second thing is still up in the air.

**Comment by janiversen** [comment]
is removed on dev.
