### ISSUE TITLE
Modbus RS485 with RTS control

### ISSUE THREAD

**Issue by Ataraxiall** [riptideio/pymodbus#686]
Hello, everyone,

I am trying to make a very simple file to consult the intensity of an energy meter,

I have it physically connected to ttS2, the address in hexadecimal is 139, length 2, function 3 and it is unit 1.

this is what I have.

`
import serial
from pymodbus.pdu import ModbusRequest
from pymodbus.client.sync import ModbusSerialClient as ModbusClient #initialize a serial RTU client instance
from pymodbus.transaction import ModbusRtuFramer

import logging
logging.basicConfig()
log = logging.getLogger()
log.setLevel(logging.DEBUG)

#count= the number of registers to read
#unit= the slave unit this request is targeting
#address= the starting address to read from

client= ModbusClient(method = "rtu", port="/dev/ttyS2",stopbits = 1, bytesize = 8, parity = 'E', baudrate= 9600, rtscts=True)
client.socket.setRTS(True)

#Connect to the serial modbus server
connection = client.connect()
print (connection)

 # address, count, slave address

#Starting add, num of reg to read, slave unit.
result= client.read_holding_registers(0x0139,2,unit= 0x01)
client.socket.setRTS(False)

print(result)

#Closes the underlying socket connection
client.close()`

but i have this error

`    client.socket.setRTS(True)
AttributeError: 'NoneType' object has no attribute 'setRTS'`

Any help please? im a pyhton noob .(

**Comment by dhoomakethu** [comment]
Can you try setting `setRTS` after the `connection = client.connect()` ? Also what version of pymodbus is this?
