### ISSUE TITLE
do support  the tcp-listener mode(modbus client base on tcp server)?

### ISSUE THREAD

**Issue by IndustrialCommunication** [riptideio/pymodbus#692]
commonly,modbus tcp client is tcp client mode, in some cloud case, need use tcp server mode listen the tcp client to connect itself.

**Comment by dhoomakethu** [comment]
@IndustrialCommunication have you looked in to [isinstance(b, bytes) ](https://github.com/riptideio/pymodbus/blob/master/examples/contrib/remote_server_context.py) and https://github.com/riptideio/pymodbus/blob/master/examples/contrib/serial_forwarder.py ? This should be something you are looking for.

**Comment by IndustrialCommunication** [comment]
that is different,  that is serial_forwarder,this is modbus client as a tcp server to listen the modbus slave to connect
![图片](https://user-images.githubusercontent.com/77141668/146473112-07ed45d6-0df1-422b-b151-812ef3140826.png)
