### ISSUE TITLE
timeout is not handled by AsyncModbusSerialClient defaults to 3 seconds

### ISSUE THREAD

**Issue by bsense-rius** [riptideio/pymodbus#705]
### Versions

* Python: 3.8
* OS: Ubuntu 20.04
* Pymodbus: 2.5.3
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: None
* Client: serial rtu - async

### Description

Calling AsyncModbusSerialClient(..., timeout=5) and actually times out after 3 seconds

### Code and Logs

```python
 # code and logs here.

```

**Comment by janiversen** [comment]
TImeout is handled in 3.0.0
