### ISSUE TITLE
Problems with rtu circutor.

### ISSUE THREAD

**Issue by Alikornio** [riptideio/pymodbus#83]
Hello. I have used modbus poll for windows for read my circutor values, and it works.

Now i want to do it with a raspberry. I had searching for a modbus library that works in modbus rtu protocol, and found this.

I didn't found great help in the documentation. 

1st i didn't know what function i have to use for read the real values form circutor. I think that is read_discrete_inputs, but didn't know it certainly.
However using it, i have other issues. Circutor's documentation say the i have to use the inquiry:
63 02 00 01 00 06 A1 8A
63->Peripheral number (mine is 1)
02->Function for input status readout (i think that the function read_discrete_input include it)
00 01->Starting address
00 06 -> Number of registers to be read
A1 8A -> CRC

So ... with that information. How i have to use the call?

I have try this: 

import logging
logging.basicConfig()
log = logging.getLogger()
log.setLevel(logging.DEBUG)
# CONNEXION

client = ModbusClient(method='rtu', port='/dev/ttyUSB0', timeout=2, baudrate=9600, stopbits=1, bytesize=8, parity="N")
print "----------------"
print ' Conexion: '+format(client.connect())
print ' '+client.**str**()
print "----------------"

client.read_discrete_inputs(1,6,unit=0x01)
print result

And this is the output:

---

 Conexion: True
##  rtu baud[9600]

DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:recv: 0x1 0x82 0x2 0xc1 0x61
DEBUG:pymodbus.factory:Factory Response[130]
DEBUG:pymodbus.transaction:adding transaction 0
DEBUG:pymodbus.transaction:getting transaction 1
Exception Response(130, 2, IllegalAddress)

Thanks

**Comment by karlp** [comment]
Looks like  your particular circutor device doesn't have 6 coils from address 1.  Perhaps they're meaning address 0/ register 1?  Perhaps your device has less than 6 available to read?  try 1/1, instead of 1/6.

On the bright side, you're getting a well formed response from your device :)
