### ISSUE TITLE
PYMOBUS returning none

### ISSUE THREAD

**Issue by tabishibly** [riptideio/pymodbus#95]
I am using pymodbus library to set up communication over tcp. When I try reading registers, it is returning "none" How do i solve this?

**Comment by WillyKaze** [comment]
Just hit the same bug. I'll investigate this.

**Comment by WillyKaze** [comment]
@tabishibly Which branch are you using ?

**Comment by oetcoleman** [comment]
I'm getting this on the python3 branch.  Suspect it might be to do with the zope.interface dependency not installing correctly.

**Comment by ellepdesk** [comment]
I'm also seeing this for ModbusSerialClient, read_holding_registers returns None for python3/pymodbus3, and a correct response for pyfon2.7/pymodbus

**Comment by WillyKaze** [comment]
Thanks for the answer, I since ported my code to use pylibmodbus. I didn't run any benchmarks between this two libs but libpymodbus with ctypes (not cffi) seems quite reactive and easy to cross-compile for BeagleBone Black
