### ISSUE TITLE
Parameter documentation do not correspond to actual parameters.

### ISSUE THREAD

**Issue by janiversen** [riptideio/pymodbus#966]
### Versions

* Python:
* OS:
* Pymodbus:
* Modbus Hardware (if used): 

### Pymodbus Specific
* Server: tcp/rtu/ascii - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description

What were you trying, what has happened, what went wrong, and what did you expect?

### Code and Logs

```python
 # code and logs here.

```

**Comment by janiversen** [comment]
@dhoomakethu The documentation is still not fixed, so why close it ?

**Comment by dhoomakethu** [comment]
ah, I saw the PR marked as merged, so closed it. Sorry for that.
